In [1]:
import polars as pl
import polars_ols
from pathlib import Path

In [2]:
SCRIPT_DIR = Path(".").absolute().resolve()
DATA_DIR = (SCRIPT_DIR.parent / "data").absolute().resolve()
PROCESSED_DATA_DIR = (SCRIPT_DIR.parent / "processed").absolute().resolve()

print(f"{DATA_DIR=}")
print(f"{PROCESSED_DATA_DIR=}")
assert DATA_DIR.is_dir()
assert PROCESSED_DATA_DIR.is_dir()

DATA_DIR=PosixPath('/Users/Naot/kristal-thesis-not-mine/data')
PROCESSED_DATA_DIR=PosixPath('/Users/Naot/kristal-thesis-not-mine/processed')

In [3]:
price_df = pl.read_parquet(PROCESSED_DATA_DIR / "price.parquet")
price_df

shape: (2_382_075, 6)
┌────────┬────────────┬──────────┬─────────┬────────────┬────────────────┐
│ ticker ┆ date       ┆ close    ┆ volume  ┆ shares     ┆ mktcap         │
│ ---    ┆ ---        ┆ ---      ┆ ---     ┆ ---        ┆ ---            │
│ str    ┆ date       ┆ f64      ┆ i64     ┆ i64        ┆ i64            │
╞════════╪════════════╪══════════╪═════════╪════════════╪════════════════╡
│ AAA    ┆ 2018-12-28 ┆ 11536.08 ┆ 1257250 ┆ 171199976  ┆ 2516639647200  │
│ AAM    ┆ 2018-12-28 ┆ 8690.97  ┆ 50      ┆ 8035701    ┆ 107678393400   │
│ ABR    ┆ 2018-12-28 ┆ 3614.97  ┆ 100     ┆ 3000000    ┆ 12300000000    │
│ ABT    ┆ 2018-12-28 ┆ 26370.64 ┆ 1350    ┆ 11497257   ┆ 462189731400   │
│ ACB    ┆ 2018-12-28 ┆ 7864.52  ┆ 2559551 ┆ 1247165130 ┆ 36916087848000 │
│ …      ┆ …          ┆ …        ┆ …       ┆ …          ┆ …              │
│ VIG    ┆ 2022-01-04 ┆ 17700.0  ┆ 1330695 ┆ 34133300   ┆ 604159410000   │
│ VIT    ┆ 2022-01-04 ┆ 21428.46 ┆ 15737   ┆ 49999664   ┆ 1169992137600  │
│ VLA    ┆ 2022-01-04 ┆ 10379.33 ┆ 55400   ┆ 1080000    ┆ 32400000000    │
│ VMC    ┆ 2022-01-04 ┆ 21043.6  ┆ 73434   ┆ 20000000   ┆ 550000000000   │
│ VMS    ┆ 2022-01-04 ┆ 15403.48 ┆ 50      ┆ 8999998    ┆ 159299964600   │
└────────┴────────────┴──────────┴─────────┴────────────┴────────────────┘

In [4]:
icb_df = pl.read_parquet(PROCESSED_DATA_DIR / "icb.parquet")
icb_df

shape: (732, 6)
┌────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┐
│ ticker ┆ icb1            ┆ icb2            ┆ icb3            ┆ icb4            ┆ icb5            │
│ ---    ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             │
│ str    ┆ str             ┆ str             ┆ str             ┆ str             ┆ str             │
╞════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╡
│ AAA    ┆ Nguyên vật liệu ┆ Hóa chất        ┆ Hóa chất        ┆ Nhựa, cao su &  ┆ Nhựa            │
│        ┆                 ┆                 ┆                 ┆ sợi             ┆                 │
│ AAM    ┆ Hàng Tiêu dùng  ┆ Thực phẩm và đồ ┆ Sản xuất thực   ┆ Nuôi trồng nông ┆ Nuôi trồng thủy │
│        ┆                 ┆ uống            ┆ phẩm            ┆ & hải sản       ┆ hải sản         │
│ AAT    ┆ Hàng Tiêu dùng  ┆ Hàng cá nhân &  ┆ Hàng cá nhân    ┆ Hàng May mặc    ┆ Hàng May mặc    │
│        ┆                 ┆ Gia dụng        ┆                 ┆                 ┆                 │
│ ABR    ┆ Công nghiệp     ┆ Hàng & Dịch vụ  ┆ Tư vấn & Hỗ trợ ┆ Tư vấn & Hỗ trợ ┆ Tư vấn & Hỗ trợ │
│        ┆                 ┆ Công nghiệp     ┆ Kinh doanh      ┆ KD              ┆ KD              │
│ ABS    ┆ Hàng Tiêu dùng  ┆ Thực phẩm và đồ ┆ Sản xuất thực   ┆ Nuôi trồng nông ┆ Trồng ngũ cốc,  │
│        ┆                 ┆ uống            ┆ phẩm            ┆ & hải sản       ┆ rau, trái cây   │
│        ┆                 ┆                 ┆                 ┆                 ┆ &…              │
│ …      ┆ …               ┆ …               ┆ …               ┆ …               ┆ …               │
│ VTV    ┆ Công nghiệp     ┆ Xây dựng và Vật ┆ Xây dựng và Vật ┆ Vật liệu xây    ┆ Vật liệu xây    │
│        ┆                 ┆ liệu            ┆ liệu            ┆ dựng & Nội thất ┆ dựng khác       │
│ VTZ    ┆ Nguyên vật liệu ┆ Hóa chất        ┆ Hóa chất        ┆ Nhựa, cao su &  ┆ Nhựa            │
│        ┆                 ┆                 ┆                 ┆ sợi             ┆                 │
│ WCS    ┆ Công nghiệp     ┆ Hàng & Dịch vụ  ┆ Vận tải         ┆ Kho bãi, hậu    ┆ Bến xe khách    │
│        ┆                 ┆ Công nghiệp     ┆                 ┆ cần và bảo      ┆                 │
│        ┆                 ┆                 ┆                 ┆ dưỡng           ┆                 │
│ WSS    ┆ Tài chính       ┆ Dịch vụ tài     ┆ Dịch vụ tài     ┆ Môi giới chứng  ┆ Môi giới chứng  │
│        ┆                 ┆ chính           ┆ chính           ┆ khoán           ┆ khoán           │
│ X20    ┆ Hàng Tiêu dùng  ┆ Hàng cá nhân &  ┆ Hàng cá nhân    ┆ Hàng May mặc    ┆ Hàng May mặc    │
│        ┆                 ┆ Gia dụng        ┆                 ┆                 ┆                 │
└────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┘

In [5]:
cleaned_price_df = (
    price_df.join(
        icb_df,
        on="ticker",
        how="left",
        validate="m:1",
    )
    .filter(pl.col("icb2").is_not_null())
    .filter(
        ~pl.col("icb2").is_in(
            [
                "Dịch vụ tài chính",
                "Ngân hàng",
                "Bảo hiểm",
            ]
        )
    )
    .filter(~pl.col("ticker").is_in(["DSC", "MIC"]))
    .with_columns(
        pl.when(pl.col("mktcap") != 0)
        .then(pl.col("mktcap"))
        .otherwise(None)
        .alias("mktcap"),
        year=pl.col("date").dt.year(),
        week=pl.col("date").dt.week(),
        dayofweek=pl.col("date").dt.weekday(),
    )
    .filter(~pl.col("dayofweek").is_in([6, 7]))
    .filter(pl.col("year") >= 2010)
    .filter(pl.col("year") <= 2024)
)
cleaned_price_df

shape: (2_012_272, 14)
┌────────┬────────────┬──────────┬─────────┬───┬─────────────────────────┬──────┬──────┬───────────┐
│ ticker ┆ date       ┆ close    ┆ volume  ┆ … ┆ icb5                    ┆ year ┆ week ┆ dayofweek │
│ ---    ┆ ---        ┆ ---      ┆ ---     ┆   ┆ ---                     ┆ ---  ┆ ---  ┆ ---       │
│ str    ┆ date       ┆ f64      ┆ i64     ┆   ┆ str                     ┆ i32  ┆ i8   ┆ i8        │
╞════════╪════════════╪══════════╪═════════╪═══╪═════════════════════════╪══════╪══════╪═══════════╡
│ AAA    ┆ 2018-12-28 ┆ 11536.08 ┆ 1257250 ┆ … ┆ Nhựa                    ┆ 2018 ┆ 52   ┆ 5         │
│ AAM    ┆ 2018-12-28 ┆ 8690.97  ┆ 50      ┆ … ┆ Nuôi trồng thủy hải sản ┆ 2018 ┆ 52   ┆ 5         │
│ ABR    ┆ 2018-12-28 ┆ 3614.97  ┆ 100     ┆ … ┆ Tư vấn & Hỗ trợ KD      ┆ 2018 ┆ 52   ┆ 5         │
│ ABT    ┆ 2018-12-28 ┆ 26370.64 ┆ 1350    ┆ … ┆ Nuôi trồng thủy hải sản ┆ 2018 ┆ 52   ┆ 5         │
│ ACC    ┆ 2018-12-28 ┆ 5718.26  ┆ 40      ┆ … ┆ Sản xuất bê tông        ┆ 2018 ┆ 52   ┆ 5         │
│ …      ┆ …          ┆ …        ┆ …       ┆ … ┆ …                       ┆ …    ┆ …    ┆ …         │
│ VIF    ┆ 2022-01-04 ┆ 17585.17 ┆ 0       ┆ … ┆ Lâm sản và Chế biến gỗ  ┆ 2022 ┆ 1    ┆ 2         │
│ VIT    ┆ 2022-01-04 ┆ 21428.46 ┆ 15737   ┆ … ┆ Sản xuất gạch ốp lát &  ┆ 2022 ┆ 1    ┆ 2         │
│        ┆            ┆          ┆         ┆   ┆ Vật liệ…                ┆      ┆      ┆           │
│ VLA    ┆ 2022-01-04 ┆ 10379.33 ┆ 55400   ┆ … ┆ Phần mềm                ┆ 2022 ┆ 1    ┆ 2         │
│ VMC    ┆ 2022-01-04 ┆ 21043.6  ┆ 73434   ┆ … ┆ Xây dựng                ┆ 2022 ┆ 1    ┆ 2         │
│ VMS    ┆ 2022-01-04 ┆ 15403.48 ┆ 50      ┆ … ┆ Dịch vụ kho bãi         ┆ 2022 ┆ 1    ┆ 2         │
└────────┴────────────┴──────────┴─────────┴───┴─────────────────────────┴──────┴──────┴───────────┘

In [6]:
wret_df = (
    cleaned_price_df.with_columns(pl.col("date").cast(pl.Date))
    .sort(["ticker", "date"])
    .upsample(time_column="date", every="1d", group_by="ticker", maintain_order=True)
    .with_columns(
        dret=(pl.col("close") / pl.col("close").shift(1)).log().over("ticker")
    )
    .filter(pl.col("close").is_not_null() | pl.col("dret").is_not_null())
    .with_columns(
        year=pl.col("date").dt.year(),
        week=pl.col("date").dt.week(),
        mktcap=pl.when(pl.col("mktcap") != 0).then(pl.col("mktcap")).otherwise(None),
    )
    .group_by(["ticker", "year", "week"])
    .agg(
        [
            pl.col("dret").sum(),
            pl.col("mktcap").last(ignore_nulls=True),
            pl.col("icb1").last(ignore_nulls=True),
            pl.col("icb2").last(ignore_nulls=True),
            pl.col("icb3").last(ignore_nulls=True),
            pl.col("icb4").last(ignore_nulls=True),
            pl.col("icb5").last(ignore_nulls=True),
        ]
    )
    # 7. Final Weekly Return and Outlier Filter
    .with_columns(wret=(pl.col("dret").exp() - 1))
    .filter(pl.col("wret").abs() < (pow(1.1, 5) - 1))
)
wret_df

shape: (401_964, 11)
┌────────┬──────┬──────┬───────────┬───┬───────────────┬───────────────┬───────────────┬───────────┐
│ ticker ┆ year ┆ week ┆ dret      ┆ … ┆ icb3          ┆ icb4          ┆ icb5          ┆ wret      │
│ ---    ┆ ---  ┆ ---  ┆ ---       ┆   ┆ ---           ┆ ---           ┆ ---           ┆ ---       │
│ str    ┆ i32  ┆ i8   ┆ f64       ┆   ┆ str           ┆ str           ┆ str           ┆ f64       │
╞════════╪══════╪══════╪═══════════╪═══╪═══════════════╪═══════════════╪═══════════════╪═══════════╡
│ VE1    ┆ 2018 ┆ 37   ┆ 0.019231  ┆ … ┆ Xây dựng và   ┆ Xây dựng      ┆ Xây dựng      ┆ 0.019417  │
│        ┆      ┆      ┆           ┆   ┆ Vật liệu      ┆               ┆               ┆           │
│ CLC    ┆ 2024 ┆ 27   ┆ 0.013699  ┆ … ┆ Thuốc lá      ┆ Thuốc lá      ┆ Thuốc lá      ┆ 0.013793  │
│ KTS    ┆ 2018 ┆ 12   ┆ -0.1494   ┆ … ┆ Sản xuất thực ┆ Thực phẩm     ┆ Đường         ┆ -0.138776 │
│        ┆      ┆      ┆           ┆   ┆ phẩm          ┆               ┆               ┆           │
│ S4A    ┆ 2020 ┆ 18   ┆ 0.0       ┆ … ┆ Sản xuất &    ┆ Sản xuất &    ┆ Sản xuất &    ┆ 0.0       │
│        ┆      ┆      ┆           ┆   ┆ Phân phối     ┆ Phân phối     ┆ Phân phối     ┆           │
│        ┆      ┆      ┆           ┆   ┆ Điện          ┆ Điện          ┆ Điện          ┆           │
│ VFG    ┆ 2022 ┆ 14   ┆ -0.04512  ┆ … ┆ Hóa chất      ┆ Sản phẩm hóa  ┆ Thuốc trừ sâu ┆ -0.044118 │
│        ┆      ┆      ┆           ┆   ┆               ┆ dầu, Nông     ┆               ┆           │
│        ┆      ┆      ┆           ┆   ┆               ┆ dược & …      ┆               ┆           │
│ …      ┆ …    ┆ …    ┆ …         ┆ … ┆ …             ┆ …             ┆ …             ┆ …         │
│ BWE    ┆ 2018 ┆ 19   ┆ -0.045053 ┆ … ┆ Nước & Khí    ┆ Nước          ┆ Nước          ┆ -0.044053 │
│        ┆      ┆      ┆           ┆   ┆ đốt           ┆               ┆               ┆           │
│ SMB    ┆ 2012 ┆ 49   ┆ 0.113191  ┆ … ┆ Bia và đồ     ┆ Sản xuất bia  ┆ Sản xuất bia  ┆ 0.119845  │
│        ┆      ┆      ┆           ┆   ┆ uống          ┆               ┆               ┆           │
│ HMH    ┆ 2024 ┆ 31   ┆ 0.04226   ┆ … ┆ Vận tải       ┆ Dịch vụ vận   ┆ Vận tải hàng  ┆ 0.043165  │
│        ┆      ┆      ┆           ┆   ┆               ┆ tải           ┆ khô           ┆           │
│ AAT    ┆ 2024 ┆ 39   ┆ -0.00545  ┆ … ┆ Hàng cá nhân  ┆ Hàng May mặc  ┆ Hàng May mặc  ┆ -0.005435 │
│ S4A    ┆ 2024 ┆ 5    ┆ 0.024132  ┆ … ┆ Sản xuất &    ┆ Sản xuất &    ┆ Sản xuất &    ┆ 0.024425  │
│        ┆      ┆      ┆           ┆   ┆ Phân phối     ┆ Phân phối     ┆ Phân phối     ┆           │
│        ┆      ┆      ┆           ┆   ┆ Điện          ┆ Điện          ┆ Điện          ┆           │
└────────┴──────┴──────┴───────────┴───┴───────────────┴───────────────┴───────────────┴───────────┘

In [7]:
vwmktret_df = (
    wret_df.sort(["ticker", "year", "week"])
    .with_columns(
        weekid=pl.int_range(0, pl.len()).over("ticker"),
        totalmktcap=pl.col("mktcap").sum().over(["year", "week"]),
    )
    .with_columns(mktcap_weighted=pl.col("mktcap") / pl.col("totalmktcap"))
    .pipe(
        lambda x: x.join(
            x.select(
                [
                    pl.col("ticker"),
                    (pl.col("weekid") + 1).alias("weekid"),
                    pl.col("mktcap_weighted").alias("mktcap_weighted_L1"),
                ]
            ),
            on=["ticker", "weekid"],
            how="left",
        )
    )
    .with_columns(wret_weighted=pl.col("mktcap_weighted_L1") * pl.col("wret"))
    .with_columns(vwmktret=pl.col("wret_weighted").sum().over(["year", "week"]))
)
vwmktret_df

shape: (401_964, 17)
┌────────┬──────┬──────┬───────────┬───┬───────────────┬───────────────┬───────────────┬───────────┐
│ ticker ┆ year ┆ week ┆ dret      ┆ … ┆ mktcap_weight ┆ mktcap_weight ┆ wret_weighted ┆ vwmktret  │
│ ---    ┆ ---  ┆ ---  ┆ ---       ┆   ┆ ed            ┆ ed_L1         ┆ ---           ┆ ---       │
│ str    ┆ i32  ┆ i8   ┆ f64       ┆   ┆ ---           ┆ ---           ┆ f64           ┆ f64       │
│        ┆      ┆      ┆           ┆   ┆ f64           ┆ f64           ┆               ┆           │
╞════════╪══════╪══════╪═══════════╪═══╪═══════════════╪═══════════════╪═══════════════╪═══════════╡
│ AAA    ┆ 2010 ┆ 28   ┆ -0.068421 ┆ … ┆ 0.001255      ┆ null          ┆ null          ┆ 0.007874  │
│ AAA    ┆ 2010 ┆ 29   ┆ -0.008565 ┆ … ┆ 0.001263      ┆ 0.001255      ┆ -0.000011     ┆ -0.011679 │
│ AAA    ┆ 2010 ┆ 30   ┆ 0.056918  ┆ … ┆ 0.001311      ┆ 0.001263      ┆ 0.000074      ┆ -0.003428 │
│ AAA    ┆ 2010 ┆ 31   ┆ -0.004073 ┆ … ┆ 0.001342      ┆ 0.001311      ┆ -0.000005     ┆ -0.013798 │
│ AAA    ┆ 2010 ┆ 32   ┆ -0.091767 ┆ … ┆ 0.001266      ┆ 0.001342      ┆ -0.000118     ┆ -0.038262 │
│ …      ┆ …    ┆ …    ┆ …         ┆ … ┆ …             ┆ …             ┆ …             ┆ …         │
│ YEG    ┆ 2024 ┆ 48   ┆ 0.041577  ┆ … ┆ 0.000492      ┆ 0.000485      ┆ 0.000021      ┆ 0.010507  │
│ YEG    ┆ 2024 ┆ 49   ┆ 0.183066  ┆ … ┆ 0.00059       ┆ 0.000492      ┆ 0.000099      ┆ 0.016263  │
│ YEG    ┆ 2024 ┆ 50   ┆ 0.024098  ┆ … ┆ 0.00065       ┆ 0.00059       ┆ 0.000014      ┆ -0.008959 │
│ YEG    ┆ 2024 ┆ 51   ┆ 0.263417  ┆ … ┆ 0.000837      ┆ 0.00065       ┆ 0.000196      ┆ 0.000594  │
│ YEG    ┆ 2024 ┆ 52   ┆ -0.009901 ┆ … ┆ 0.00088       ┆ 0.000837      ┆ -0.000008     ┆ 0.002368  │
└────────┴──────┴──────┴───────────┴───┴───────────────┴───────────────┴───────────────┴───────────┘

In [8]:
vwindret_df = (
    vwmktret_df.with_columns(
        total_mktcap_ind=pl.col("mktcap").sum().over(["icb1", "year", "week"])
    )
    .with_columns(ind_weight=pl.col("mktcap") / pl.col("total_mktcap_ind"))
    .pipe(
        lambda x: x.join(
            x.select(
                [
                    pl.col("ticker"),
                    (pl.col("weekid") + 1).alias("weekid"),
                    pl.col("ind_weight").alias("ind_weight_L1"),
                ]
            ),
            on=["ticker", "weekid"],
            how="left",
        )
    )
    .with_columns(ind_wret_weighted=pl.col("ind_weight_L1") * pl.col("wret"))
    .with_columns(
        vwindret=pl.col("ind_wret_weighted").sum().over(["icb1", "year", "week"])
    )
)
vwindret_df

shape: (401_964, 22)
┌────────┬──────┬──────┬───────────┬───┬────────────┬───────────────┬──────────────────┬───────────┐
│ ticker ┆ year ┆ week ┆ dret      ┆ … ┆ ind_weight ┆ ind_weight_L1 ┆ ind_wret_weighte ┆ vwindret  │
│ ---    ┆ ---  ┆ ---  ┆ ---       ┆   ┆ ---        ┆ ---           ┆ d                ┆ ---       │
│ str    ┆ i32  ┆ i8   ┆ f64       ┆   ┆ f64        ┆ f64           ┆ ---              ┆ f64       │
│        ┆      ┆      ┆           ┆   ┆            ┆               ┆ f64              ┆           │
╞════════╪══════╪══════╪═══════════╪═══╪════════════╪═══════════════╪══════════════════╪═══════════╡
│ AAA    ┆ 2010 ┆ 28   ┆ -0.068421 ┆ … ┆ 0.009007   ┆ null          ┆ null             ┆ 0.011574  │
│ AAA    ┆ 2010 ┆ 29   ┆ -0.008565 ┆ … ┆ 0.009064   ┆ 0.009007      ┆ -0.000077        ┆ -0.00809  │
│ AAA    ┆ 2010 ┆ 30   ┆ 0.056918  ┆ … ┆ 0.00963    ┆ 0.009064      ┆ 0.000531         ┆ -0.012907 │
│ AAA    ┆ 2010 ┆ 31   ┆ -0.004073 ┆ … ┆ 0.009714   ┆ 0.00963       ┆ -0.000039        ┆ 0.003191  │
│ AAA    ┆ 2010 ┆ 32   ┆ -0.091767 ┆ … ┆ 0.00933    ┆ 0.009714      ┆ -0.000852        ┆ -0.040773 │
│ …      ┆ …    ┆ …    ┆ …         ┆ … ┆ …          ┆ …             ┆ …                ┆ …         │
│ YEG    ┆ 2024 ┆ 48   ┆ 0.041577  ┆ … ┆ 0.005622   ┆ 0.005585      ┆ 0.000237         ┆ 0.014501  │
│ YEG    ┆ 2024 ┆ 49   ┆ 0.183066  ┆ … ┆ 0.006869   ┆ 0.005622      ┆ 0.001129         ┆ -0.007632 │
│ YEG    ┆ 2024 ┆ 50   ┆ 0.024098  ┆ … ┆ 0.007517   ┆ 0.006869      ┆ 0.000168         ┆ -0.006927 │
│ YEG    ┆ 2024 ┆ 51   ┆ 0.263417  ┆ … ┆ 0.00953    ┆ 0.007517      ┆ 0.002265         ┆ 0.011113  │
│ YEG    ┆ 2024 ┆ 52   ┆ -0.009901 ┆ … ┆ 0.009987   ┆ 0.00953       ┆ -0.000094        ┆ -0.003585 │
└────────┴──────┴──────┴───────────┴───┴────────────┴───────────────┴──────────────────┴───────────┘

In [13]:
ols_df = (
    vwindret_df.sort(
        ["ticker", "year", "week"]
    )  # <--- Optional but recommended safety net
    .with_columns(
        vwmktret_L1=pl.col("vwmktret").shift(1).over("ticker"),
        vwmktret_F1=pl.col("vwmktret").shift(-1).over("ticker"),
        vwindret_L1=pl.col("vwindret").shift(1).over("ticker"),
        vwindret_F1=pl.col("vwindret").shift(-1).over("ticker"),
    )
    .with_columns(
        ols_res=pl.col("wret")
        .least_squares.rolling_ols(
            pl.col("vwmktret_L1"),
            pl.col("vwmktret"),
            pl.col("vwmktret_F1"),
            pl.col("vwindret_L1"),
            pl.col("vwindret"),
            pl.col("vwindret_F1"),
            window_size=53,
            min_periods=26,
            add_intercept=True,
            mode="coefficients",
        )
        .over("ticker")
    )
    .filter(pl.col("ols_res").is_not_null())
    .with_columns(
        b_vwmktret_L1=pl.col("ols_res").struct.field("vwmktret_L1"),
        b_vwmktret=pl.col("ols_res").struct.field("vwmktret"),
        b_vwmktret_F1=pl.col("ols_res").struct.field("vwmktret_F1"),
        b_vwindret_L1=pl.col("ols_res").struct.field("vwindret_L1"),
        b_vwindret=pl.col("ols_res").struct.field("vwindret"),
        b_vwindret_F1=pl.col("ols_res").struct.field("vwindret_F1"),
        b_cons=pl.col("ols_res").struct.field("const"),
    )
    .with_columns(
        e=pl.col("wret")
        - (
            pl.col("b_vwmktret_L1") * pl.col("vwmktret_L1")
            + pl.col("b_vwmktret") * pl.col("vwmktret")
            + pl.col("b_vwmktret_F1") * pl.col("vwmktret_F1")
            + pl.col("b_vwindret_L1") * pl.col("vwindret_L1")
            + pl.col("b_vwindret") * pl.col("vwindret")
            + pl.col("b_vwindret_F1") * pl.col("vwindret_F1")
            + pl.col("b_cons")
        )
    )
    .with_columns(W=pl.col("e").log1p())
    .drop_nulls(subset=["W"])
    .drop(["e", "ols_res"])
)
ols_df

shape: (384_815, 34)
┌────────┬──────┬──────┬─────────────┬───┬────────────┬───────────────┬───────────┬───────────┐
│ ticker ┆ year ┆ week ┆ dret        ┆ … ┆ b_vwindret ┆ b_vwindret_F1 ┆ b_cons    ┆ W         │
│ ---    ┆ ---  ┆ ---  ┆ ---         ┆   ┆ ---        ┆ ---           ┆ ---       ┆ ---       │
│ str    ┆ i32  ┆ i8   ┆ f64         ┆   ┆ f64        ┆ f64           ┆ f64       ┆ f64       │
╞════════╪══════╪══════╪═════════════╪═══╪════════════╪═══════════════╪═══════════╪═══════════╡
│ AAA    ┆ 2011 ┆ 2    ┆ 0.008733    ┆ … ┆ 3.427124   ┆ 0.934459      ┆ 0.002225  ┆ -0.073005 │
│ AAA    ┆ 2011 ┆ 3    ┆ 0.069376    ┆ … ┆ 2.828251   ┆ 0.760462      ┆ -0.000756 ┆ -0.047181 │
│ AAA    ┆ 2011 ┆ 4    ┆ -1.0061e-16 ┆ … ┆ 2.846664   ┆ 0.783306      ┆ -0.000275 ┆ 0.009961  │
│ AAA    ┆ 2011 ┆ 6    ┆ 0.002912    ┆ … ┆ 2.344612   ┆ 0.14878       ┆ 0.002952  ┆ 0.078881  │
│ AAA    ┆ 2011 ┆ 7    ┆ -0.029327   ┆ … ┆ 1.99985    ┆ -0.088366     ┆ 0.004303  ┆ 0.046757  │
│ …      ┆ …    ┆ …    ┆ …           ┆ … ┆ …          ┆ …             ┆ …         ┆ …         │
│ YEG    ┆ 2024 ┆ 47   ┆ -0.045463   ┆ … ┆ 0.01769    ┆ -0.652802     ┆ 0.002136  ┆ -0.042082 │
│ YEG    ┆ 2024 ┆ 48   ┆ 0.041577    ┆ … ┆ 0.032733   ┆ -0.637421     ┆ 0.001512  ┆ 0.002543  │
│ YEG    ┆ 2024 ┆ 49   ┆ 0.183066    ┆ … ┆ -0.306844  ┆ -0.671661     ┆ 0.005374  ┆ 0.161866  │
│ YEG    ┆ 2024 ┆ 50   ┆ 0.024098    ┆ … ┆ -0.346402  ┆ -0.641257     ┆ 0.005506  ┆ 0.042889  │
│ YEG    ┆ 2024 ┆ 51   ┆ 0.263417    ┆ … ┆ -0.199229  ┆ -0.959995     ┆ 0.010365  ┆ 0.25191   │
└────────┴──────┴──────┴─────────────┴───┴────────────┴───────────────┴───────────┴───────────┘

In [16]:
df_stats = ols_df.sort(["ticker", "year", "week"]).with_columns(
    RET=pl.col("W").mean().over(["ticker", "year"]),
    STDEV=pl.col("W").std().over(["ticker", "year"]),
)
df_stats

shape: (384_815, 36)
┌────────┬──────┬──────┬─────────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ticker ┆ year ┆ week ┆ dret        ┆ … ┆ b_cons    ┆ W         ┆ RET       ┆ STDEV    │
│ ---    ┆ ---  ┆ ---  ┆ ---         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str    ┆ i32  ┆ i8   ┆ f64         ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞════════╪══════╪══════╪═════════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ AAA    ┆ 2011 ┆ 2    ┆ 0.008733    ┆ … ┆ 0.002225  ┆ -0.073005 ┆ -0.002458 ┆ 0.052178 │
│ AAA    ┆ 2011 ┆ 3    ┆ 0.069376    ┆ … ┆ -0.000756 ┆ -0.047181 ┆ -0.002458 ┆ 0.052178 │
│ AAA    ┆ 2011 ┆ 4    ┆ -1.0061e-16 ┆ … ┆ -0.000275 ┆ 0.009961  ┆ -0.002458 ┆ 0.052178 │
│ AAA    ┆ 2011 ┆ 6    ┆ 0.002912    ┆ … ┆ 0.002952  ┆ 0.078881  ┆ -0.002458 ┆ 0.052178 │
│ AAA    ┆ 2011 ┆ 7    ┆ -0.029327   ┆ … ┆ 0.004303  ┆ 0.046757  ┆ -0.002458 ┆ 0.052178 │
│ …      ┆ …    ┆ …    ┆ …           ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ YEG    ┆ 2024 ┆ 47   ┆ -0.045463   ┆ … ┆ 0.002136  ┆ -0.042082 ┆ 0.006286  ┆ 0.058895 │
│ YEG    ┆ 2024 ┆ 48   ┆ 0.041577    ┆ … ┆ 0.001512  ┆ 0.002543  ┆ 0.006286  ┆ 0.058895 │
│ YEG    ┆ 2024 ┆ 49   ┆ 0.183066    ┆ … ┆ 0.005374  ┆ 0.161866  ┆ 0.006286  ┆ 0.058895 │
│ YEG    ┆ 2024 ┆ 50   ┆ 0.024098    ┆ … ┆ 0.005506  ┆ 0.042889  ┆ 0.006286  ┆ 0.058895 │
│ YEG    ┆ 2024 ┆ 51   ┆ 0.263417    ┆ … ┆ 0.010365  ┆ 0.25191   ┆ 0.006286  ┆ 0.058895 │
└────────┴──────┴──────┴─────────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df_crash = (
    df_stats
    # 1. Sort the data
    .sort(["ticker", "year", "week"])
    # 2. Pre-collapse variable generation
    .with_columns(
        W2=pl.col("W").pow(2),
        W3=pl.col("W").pow(3),
        # In Stata, 'if' leaves the value as missing (.) when false. We use 'None' to mimic this.
        W_up2=pl.when(pl.col("W") > pl.col("RET"))
        .then(pl.col("W").pow(2))
        .otherwise(None),
        W_down2=pl.when(pl.col("W") < pl.col("RET"))
        .then(pl.col("W").pow(2))
        .otherwise(None),
        # Flag extreme negative returns (>= 3.09 std devs)
        DCRASH=pl.when(pl.col("W").abs() >= 3.09 * pl.col("STDEV"))
        .then(1)
        .otherwise(0),
    )
    # 3. Collapse (Aggregate to the Year level)
    .group_by(["ticker", "year"], maintain_order=True)
    .agg(
        [
            # (count) maps to .count() because Polars' count() correctly ignores nulls
            pl.col("W").count().alias("W"),  # Note: W is now the 'N' count!
            pl.col("W_up2").count().alias("n_up"),
            pl.col("W_down2").count().alias("n_down"),
            # (sum)
            pl.col("W2").sum(),
            pl.col("W3").sum(),
            pl.col("W_up2").sum(),
            pl.col("W_down2").sum(),
            pl.col("DCRASH").sum(),
            # (lastnm)
            pl.col("mktcap").last(ignore_nulls=True),
            pl.col("icb1").last(ignore_nulls=True),
            pl.col("icb2").last(ignore_nulls=True),
            pl.col("icb3").last(ignore_nulls=True),
            pl.col("icb4").last(ignore_nulls=True),
            pl.col("icb5").last(ignore_nulls=True),
            pl.col("RET").last(ignore_nulls=True),
            pl.col("STDEV").last(ignore_nulls=True),
        ]
    )
    # 4. Post-collapse Skewness and Volatility math
    .with_columns(
        # Stata evaluates (3/2) as 1.5. Using .pow(1.5) is the strict mathematical equivalent.
        NCSKEW1=pl.col("W") * (pl.col("W") - 1).pow(1.5) * pl.col("W3"),
        NCSKEW2=(pl.col("W") - 1) * (pl.col("W") - 2) * pl.col("W2").pow(1.5),
    )
    .with_columns(
        NCSKEW=-pl.col("NCSKEW1") / pl.col("NCSKEW2"),
        # Natural log is .log() in Polars
        DUVOL=(
            ((pl.col("n_up") - 1) * pl.col("W_down2"))
            / ((pl.col("n_down") - 1) * pl.col("W_up2"))
        ).log(),
        # replace DCRASH=1 if DCRASH>0 (Since we summed it, any positive value means at least 1 crash week)
        DCRASH=pl.when(pl.col("DCRASH") > 0).then(1).otherwise(0),
    )
    # (Optional) Drop intermediate calculation columns if you want a clean final dataset
    # .drop(["W2", "W3", "W_up2", "W_down2", "NCSKEW1", "NCSKEW2", "n_up", "n_down"])
)

df_crash

shape: (7_785, 22)
┌────────┬──────┬─────┬──────┬───┬─────────────┬────────────┬───────────┬───────────┐
│ ticker ┆ year ┆ W   ┆ n_up ┆ … ┆ NCSKEW1     ┆ NCSKEW2    ┆ NCSKEW    ┆ DUVOL     │
│ ---    ┆ ---  ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---        ┆ ---       ┆ ---       │
│ str    ┆ i32  ┆ u32 ┆ u32  ┆   ┆ f64         ┆ f64        ┆ f64       ┆ f64       │
╞════════╪══════╪═════╪══════╪═══╪═════════════╪════════════╪═══════════╪═══════════╡
│ AAA    ┆ 2011 ┆ 50  ┆ 24   ┆ … ┆ -35.197463  ┆ 114.993744 ┆ 0.306082  ┆ 0.129243  │
│ AAA    ┆ 2012 ┆ 51  ┆ 28   ┆ … ┆ -21.370587  ┆ 70.172236  ┆ 0.304545  ┆ 0.504287  │
│ AAA    ┆ 2013 ┆ 51  ┆ 25   ┆ … ┆ 15.025375   ┆ 16.713754  ┆ -0.898983 ┆ -0.621924 │
│ AAA    ┆ 2014 ┆ 52  ┆ 29   ┆ … ┆ -18.09335   ┆ 73.140051  ┆ 0.24738   ┆ 0.350751  │
│ AAA    ┆ 2015 ┆ 51  ┆ 28   ┆ … ┆ -16.32759   ┆ 35.867244  ┆ 0.455223  ┆ 0.591367  │
│ …      ┆ …    ┆ …   ┆ …    ┆ … ┆ …           ┆ …          ┆ …         ┆ …         │
│ YEG    ┆ 2020 ┆ 53  ┆ 25   ┆ … ┆ 540.473144  ┆ 294.786438 ┆ -1.83344  ┆ -1.439329 │
│ YEG    ┆ 2021 ┆ 52  ┆ 29   ┆ … ┆ -258.476848 ┆ 252.074178 ┆ 1.0254    ┆ 0.838275  │
│ YEG    ┆ 2022 ┆ 51  ┆ 21   ┆ … ┆ 137.644701  ┆ 298.54999  ┆ -0.461044 ┆ -0.589845 │
│ YEG    ┆ 2023 ┆ 52  ┆ 22   ┆ … ┆ 257.275283  ┆ 187.199439 ┆ -1.374338 ┆ -1.309652 │
│ YEG    ┆ 2024 ┆ 51  ┆ 22   ┆ … ┆ 336.842998  ┆ 180.0486   ┆ -1.870845 ┆ -1.203508 │
└────────┴──────┴─────┴──────┴───┴─────────────┴────────────┴───────────┴───────────┘