In [2]:
import polars as pl
import pandas as pd
from pathlib import Path

In [3]:
SCRIPT_DIR = Path(".").absolute().resolve()
DATA_DIR = (SCRIPT_DIR.parent / "data").absolute().resolve()
PROCESSED_DATA_DIR = (SCRIPT_DIR.parent / "processed").absolute().resolve()

print(f"{DATA_DIR=}")
print(f"{PROCESSED_DATA_DIR=}")
assert DATA_DIR.is_dir()
assert PROCESSED_DATA_DIR.is_dir()

DATA_DIR=PosixPath('/Users/Naot/kristal-thesis-not-mine/data')
PROCESSED_DATA_DIR=PosixPath('/Users/Naot/kristal-thesis-not-mine/processed')

In [4]:
df = pl.read_excel(DATA_DIR / "HOSE/Excel/101-200_HNX_2007-2010.xlsx")

df

Could not determine dtype for column 8, falling back to string

shape: (21_482, 28)
┌───────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ No    ┆ Ticker ┆ Company    ┆ Date       ┆ … ┆ Volume     ┆ Average    ┆ Average    ┆ Average    │
│ ---   ┆ ---    ┆ Name       ┆ ---        ┆   ┆ weighted   ┆ Volume 1   ┆ Volume 1   ┆ Volume 1   │
│ i64   ┆ str    ┆ ---        ┆ date       ┆   ┆ average    ┆ week       ┆ month      ┆ year       │
│       ┆        ┆ str        ┆            ┆   ┆ price …    ┆ Unit: Sh…  ┆ Unit: S…   ┆ Unit: Sh…  │
│       ┆        ┆            ┆            ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│       ┆        ┆            ┆            ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞═══════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 1     ┆ ICG    ┆ Song Hong  ┆ 2010-12-31 ┆ … ┆ 28625      ┆ 244340     ┆ 555452     ┆ 405546     │
│       ┆        ┆ Constructi ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ on         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 2     ┆ IDJ    ┆ IDJ Invest ┆ 2010-12-31 ┆ … ┆ null       ┆ 595080     ┆ 1092400    ┆ null       │
│       ┆        ┆ ment., JSC ┆            ┆   ┆            ┆            ┆            ┆            │
│ 3     ┆ IDV    ┆ Vinh Phuc  ┆ 2010-12-31 ┆ … ┆ null       ┆ 2380       ┆ 943        ┆ null       │
│       ┆        ┆ Infrastruc ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ ture       ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ Devel…     ┆            ┆   ┆            ┆            ┆            ┆            │
│ 4     ┆ INC    ┆ IDICO      ┆ 2010-12-31 ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│       ┆        ┆ Investment ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ Consultanc ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ y          ┆            ┆   ┆            ┆            ┆            ┆            │
│ 5     ┆ INN    ┆ Agricultur ┆ 2010-12-31 ┆ … ┆ null       ┆ 700        ┆ 2095       ┆ null       │
│       ┆        ┆ e Printing ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ And Packa… ┆            ┆   ┆            ┆            ┆            ┆            │
│ …     ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 21478 ┆ PJC    ┆ Petrolimex ┆ 2007-01-02 ┆ … ┆ null       ┆ 0          ┆ null       ┆ null       │
│       ┆        ┆ Hanoi Tran ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ sportatio… ┆            ┆   ┆            ┆            ┆            ┆            │
│ 21479 ┆ PLC    ┆ Petrolimex ┆ 2007-01-02 ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│       ┆        ┆ Petrochemi ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ cal        ┆            ┆   ┆            ┆            ┆            ┆            │
│ 21480 ┆ POT    ┆ Post and   ┆ 2007-01-02 ┆ … ┆ null       ┆ 37900      ┆ null       ┆ null       │
│       ┆        ┆ Telecom    ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ Equipments ┆            ┆   ┆            ┆            ┆            ┆            │
│ 21481 ┆ PSC    ┆ Sai Gon    ┆ 2007-01-02 ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│       ┆        ┆ Petrolimex ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ Transporta ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ t…         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 21482 ┆ PTS    ┆ Hai Phong  ┆ 2007-01-02 ┆ … ┆ null       ┆ 2925       ┆ 3452       ┆ null       │
│       ┆        ┆ Petrolimex ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ Transport… ┆            ┆   ┆            ┆            ┆            ┆            │
└───────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [5]:
df.select(pl.col("Adjusted Rate (D)\nUnit: %").n_unique())

shape: (1, 1)
┌───────────────────┐
│ Adjusted Rate (D) │
│ Unit: %           │
│ ---               │
│ u32               │
╞═══════════════════╡
│ 1                 │
└───────────────────┘

In [6]:
df.columns

['No',
 'Ticker',
 'Company Name',
 'Date',
 'Close Adjusted (D)\nUnit: VND',
 'Total trading volume (D)\nUnit: Shares',
 'Reference Adjusted (D)\nUnit: VND',
 '% Change (D)\nUnit: %',
 'Adjusted Rate (D)\nUnit: %',
 'Weighted Average Outstanding Shares\nUnit: Shares',
 'Weighted Average Diluted Outstanding Shares\nUnit: Shares',
 'Current Outstanding Shares\nUnit: Shares',
 'Market Capitalization \nUnit: VND',
 '% Price Change 1 day\nUnit: %',
 '% Price Change 1 week\nUnit: %',
 '% Price Change 1 month\nUnit: %',
 '% Price Change 1 year\nUnit: %',
 'Price Change 1 day\nUnit: VND',
 'Price Change 1 week\nUnit: VND',
 'Price Change 1 month\nUnit: VND',
 'Price Change 1 year\nUnit: VND',
 'Volume weighted average price (VWAP) 1 day\nUnit: VND',
 'Volume weighted average price (VWAP) 1 week\nUnit: VND',
 'Volume weighted average price (VWAP) 1 month\nUnit: VND',
 'Volume weighted average price (VWAP) 1 year\nUnit: VND',
 'Average Volume 1 week\nUnit: Shares',
 'Average Volume 1 month\nUnit: Shares',
 'Average Volume 1 year\nUnit: Shares']

In [7]:
df = pl.read_parquet(PROCESSED_DATA_DIR / "price.parquet")
# df.filter(pl.col("ticker").str.len_chars() != 3)
# df.select(pl.col("ticker").n_unique())
df

shape: (2_382_075, 6)
┌────────┬────────────┬──────────┬─────────┬────────────┬────────────────┐
│ ticker ┆ date       ┆ close    ┆ volume  ┆ shares     ┆ mktcap         │
│ ---    ┆ ---        ┆ ---      ┆ ---     ┆ ---        ┆ ---            │
│ str    ┆ date       ┆ f64      ┆ i64     ┆ i64        ┆ i64            │
╞════════╪════════════╪══════════╪═════════╪════════════╪════════════════╡
│ AAA    ┆ 2018-12-28 ┆ 11536.08 ┆ 1257250 ┆ 171199976  ┆ 2516639647200  │
│ AAM    ┆ 2018-12-28 ┆ 8690.97  ┆ 50      ┆ 8035701    ┆ 107678393400   │
│ ABR    ┆ 2018-12-28 ┆ 3614.97  ┆ 100     ┆ 3000000    ┆ 12300000000    │
│ ABT    ┆ 2018-12-28 ┆ 26370.64 ┆ 1350    ┆ 11497257   ┆ 462189731400   │
│ ACB    ┆ 2018-12-28 ┆ 7864.52  ┆ 2559551 ┆ 1247165130 ┆ 36916087848000 │
│ …      ┆ …          ┆ …        ┆ …       ┆ …          ┆ …              │
│ VIG    ┆ 2022-01-04 ┆ 17700.0  ┆ 1330695 ┆ 34133300   ┆ 604159410000   │
│ VIT    ┆ 2022-01-04 ┆ 21428.46 ┆ 15737   ┆ 49999664   ┆ 1169992137600  │
│ VLA    ┆ 2022-01-04 ┆ 10379.33 ┆ 55400   ┆ 1080000    ┆ 32400000000    │
│ VMC    ┆ 2022-01-04 ┆ 21043.6  ┆ 73434   ┆ 20000000   ┆ 550000000000   │
│ VMS    ┆ 2022-01-04 ┆ 15403.48 ┆ 50      ┆ 8999998    ┆ 159299964600   │
└────────┴────────────┴──────────┴─────────┴────────────┴────────────────┘

In [8]:
pl.read_excel(DATA_DIR / "INFO/ICB.xlsx")

shape: (732, 9)
┌─────┬─────┬───────────────┬──────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ STT ┆ Mã  ┆ Tên công ty   ┆ Sàn  ┆ … ┆ Phân ngành - ┆ Phân ngành - ┆ Phân ngành - ┆ Phân ngành - │
│ --- ┆ --- ┆ ---           ┆ ---  ┆   ┆ ICB L4       ┆ ICB L3       ┆ ICB L2       ┆ ICB L1       │
│ i64 ┆ str ┆ str           ┆ str  ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│     ┆     ┆               ┆      ┆   ┆ str          ┆ str          ┆ str          ┆ str          │
╞═════╪═════╪═══════════════╪══════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 1   ┆ AAA ┆ An Phát       ┆ HOSE ┆ … ┆ Nhựa, cao su ┆ Hóa chất     ┆ Hóa chất     ┆ Nguyên vật   │
│     ┆     ┆ Bioplastics   ┆      ┆   ┆ & sợi        ┆              ┆              ┆ liệu         │
│ 2   ┆ AAM ┆ Thủy sản      ┆ HOSE ┆ … ┆ Nuôi trồng   ┆ Sản xuất     ┆ Thực phẩm và ┆ Hàng Tiêu    │
│     ┆     ┆ Mekong        ┆      ┆   ┆ nông & hải   ┆ thực phẩm    ┆ đồ uống      ┆ dùng         │
│     ┆     ┆               ┆      ┆   ┆ sản          ┆              ┆              ┆              │
│ 3   ┆ AAT ┆ Tập đoàn Tiên ┆ HOSE ┆ … ┆ Hàng May mặc ┆ Hàng cá nhân ┆ Hàng cá nhân ┆ Hàng Tiêu    │
│     ┆     ┆ Sơn Thanh Hóa ┆      ┆   ┆              ┆              ┆ & Gia dụng   ┆ dùng         │
│ 4   ┆ ABR ┆ Đầu tư Nhãn   ┆ HOSE ┆ … ┆ Tư vấn & Hỗ  ┆ Tư vấn & Hỗ  ┆ Hàng & Dịch  ┆ Công nghiệp  │
│     ┆     ┆ Hiệu Việt     ┆      ┆   ┆ trợ KD       ┆ trợ Kinh     ┆ vụ Công      ┆              │
│     ┆     ┆               ┆      ┆   ┆              ┆ doanh        ┆ nghiệp       ┆              │
│ 5   ┆ ABS ┆ DV Nông       ┆ HOSE ┆ … ┆ Nuôi trồng   ┆ Sản xuất     ┆ Thực phẩm và ┆ Hàng Tiêu    │
│     ┆     ┆ nghiệp Bình   ┆      ┆   ┆ nông & hải   ┆ thực phẩm    ┆ đồ uống      ┆ dùng         │
│     ┆     ┆ Thuận         ┆      ┆   ┆ sản          ┆              ┆              ┆              │
│ …   ┆ …   ┆ …             ┆ …    ┆ … ┆ …            ┆ …            ┆ …            ┆ …            │
│ 728 ┆ VTV ┆ Năng lượng và ┆ HNX  ┆ … ┆ Vật liệu xây ┆ Xây dựng và  ┆ Xây dựng và  ┆ Công nghiệp  │
│     ┆     ┆ Môi trường    ┆      ┆   ┆ dựng & Nội   ┆ Vật liệu     ┆ Vật liệu     ┆              │
│     ┆     ┆ VICEM         ┆      ┆   ┆ thất         ┆              ┆              ┆              │
│ 729 ┆ VTZ ┆ Nhựa Việt     ┆ HNX  ┆ … ┆ Nhựa, cao su ┆ Hóa chất     ┆ Hóa chất     ┆ Nguyên vật   │
│     ┆     ┆ Thành         ┆      ┆   ┆ & sợi        ┆              ┆              ┆ liệu         │
│ 730 ┆ WCS ┆ Bến xe Miền   ┆ HNX  ┆ … ┆ Kho bãi, hậu ┆ Vận tải      ┆ Hàng & Dịch  ┆ Công nghiệp  │
│     ┆     ┆ Tây           ┆      ┆   ┆ cần và bảo   ┆              ┆ vụ Công      ┆              │
│     ┆     ┆               ┆      ┆   ┆ dưỡng        ┆              ┆ nghiệp       ┆              │
│ 731 ┆ WSS ┆ Chứng khoán   ┆ HNX  ┆ … ┆ Môi giới     ┆ Dịch vụ tài  ┆ Dịch vụ tài  ┆ Tài chính    │
│     ┆     ┆ Phố Wall      ┆      ┆   ┆ chứng khoán  ┆ chính        ┆ chính        ┆              │
│ 732 ┆ X20 ┆ May mặc X20   ┆ HNX  ┆ … ┆ Hàng May mặc ┆ Hàng cá nhân ┆ Hàng cá nhân ┆ Hàng Tiêu    │
│     ┆     ┆               ┆      ┆   ┆              ┆              ┆ & Gia dụng   ┆ dùng         │
└─────┴─────┴───────────────┴──────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

In [9]:
rename_mapping = {
    "Mã": "ticker",
    "Phân ngành - ICB L1": "icb1",
    "Phân ngành - ICB L2": "icb2",
    "Phân ngành - ICB L3": "icb3",
    "Phân ngành - ICB L4": "icb4",
    "Phân ngành - ICB L5": "icb5",
}

df = (
    pl.read_excel(DATA_DIR / "INFO/ICB.xlsx", columns=list(rename_mapping.keys()))
    .rename(rename_mapping)
    .filter(pl.col("ticker") != "")
)

df

shape: (732, 6)
┌────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┐
│ ticker ┆ icb1            ┆ icb2            ┆ icb3            ┆ icb4            ┆ icb5            │
│ ---    ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             │
│ str    ┆ str             ┆ str             ┆ str             ┆ str             ┆ str             │
╞════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╡
│ AAA    ┆ Nguyên vật liệu ┆ Hóa chất        ┆ Hóa chất        ┆ Nhựa, cao su &  ┆ Nhựa            │
│        ┆                 ┆                 ┆                 ┆ sợi             ┆                 │
│ AAM    ┆ Hàng Tiêu dùng  ┆ Thực phẩm và đồ ┆ Sản xuất thực   ┆ Nuôi trồng nông ┆ Nuôi trồng thủy │
│        ┆                 ┆ uống            ┆ phẩm            ┆ & hải sản       ┆ hải sản         │
│ AAT    ┆ Hàng Tiêu dùng  ┆ Hàng cá nhân &  ┆ Hàng cá nhân    ┆ Hàng May mặc    ┆ Hàng May mặc    │
│        ┆                 ┆ Gia dụng        ┆                 ┆                 ┆                 │
│ ABR    ┆ Công nghiệp     ┆ Hàng & Dịch vụ  ┆ Tư vấn & Hỗ trợ ┆ Tư vấn & Hỗ trợ ┆ Tư vấn & Hỗ trợ │
│        ┆                 ┆ Công nghiệp     ┆ Kinh doanh      ┆ KD              ┆ KD              │
│ ABS    ┆ Hàng Tiêu dùng  ┆ Thực phẩm và đồ ┆ Sản xuất thực   ┆ Nuôi trồng nông ┆ Trồng ngũ cốc,  │
│        ┆                 ┆ uống            ┆ phẩm            ┆ & hải sản       ┆ rau, trái cây   │
│        ┆                 ┆                 ┆                 ┆                 ┆ &…              │
│ …      ┆ …               ┆ …               ┆ …               ┆ …               ┆ …               │
│ VTV    ┆ Công nghiệp     ┆ Xây dựng và Vật ┆ Xây dựng và Vật ┆ Vật liệu xây    ┆ Vật liệu xây    │
│        ┆                 ┆ liệu            ┆ liệu            ┆ dựng & Nội thất ┆ dựng khác       │
│ VTZ    ┆ Nguyên vật liệu ┆ Hóa chất        ┆ Hóa chất        ┆ Nhựa, cao su &  ┆ Nhựa            │
│        ┆                 ┆                 ┆                 ┆ sợi             ┆                 │
│ WCS    ┆ Công nghiệp     ┆ Hàng & Dịch vụ  ┆ Vận tải         ┆ Kho bãi, hậu    ┆ Bến xe khách    │
│        ┆                 ┆ Công nghiệp     ┆                 ┆ cần và bảo      ┆                 │
│        ┆                 ┆                 ┆                 ┆ dưỡng           ┆                 │
│ WSS    ┆ Tài chính       ┆ Dịch vụ tài     ┆ Dịch vụ tài     ┆ Môi giới chứng  ┆ Môi giới chứng  │
│        ┆                 ┆ chính           ┆ chính           ┆ khoán           ┆ khoán           │
│ X20    ┆ Hàng Tiêu dùng  ┆ Hàng cá nhân &  ┆ Hàng cá nhân    ┆ Hàng May mặc    ┆ Hàng May mặc    │
│        ┆                 ┆ Gia dụng        ┆                 ┆                 ┆                 │
└────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┘

In [10]:
df = pl.read_excel(DATA_DIR / "BCTC/XLXS/2007.xlsx")

df.columns

['STT',
 'Mã',
 'Tên công ty',
 'Sàn',
 'year',
 'I. TÀI SẢN NGẮN HẠN\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền và tương đương tiền \nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1. Tiền\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.2. Các khoản tương đương tiền\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Đầu tư tài chính ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1. Chứng khoán kinh doanh\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2. Dự phòng giảm giá chứng khoán kinh doanh\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3. Đầu tư nắm giữ đến ngày đáo hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Các khoản phải thu ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.1. Phải thu ngắn hạn của khách hàng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.2. Trả trước cho người bán ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.3. Phải thu nội bộ ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.4. Phải thu theo tiến độ kế hoạch hợp đồng xây dựng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.5. Phải thu về cho vay ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.6. Phải thu ngắn hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.7. Dự phòng phải thu ngắn hạn khó đòi\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.8. Tài sản thiếu chờ xử lý\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Hàng tồn kho, ròng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4.1. Hàng tồn kho\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4.2. Dự phòng giảm giá HTK\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tài sản ngắn hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.1. Chi phí trả trước ngắn hạn \nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.2. Thuế GTGT được khấu trừ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.3. Thuế và các khoản khác phải thu Nhà nước\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.4. Giao dịch mua bán lại trái phiếu chính phủ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.5. Tài sản ngắn hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'II. TÀI SẢN DÀI HẠN\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Phải thu dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1. Phải thu khách hang dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.2. Trả trước người bán dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.3. Vốn kinh doanh ở các đơn vị trực thuộc\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.4. Phải thu nội bộ dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.5. Phải thu về cho vay dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.6. Phải thu dài hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.7. Dự phòng phải thu dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tài sản cố định\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1. GTCL TSCĐ hữu hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1.1. Nguyên giá TSCĐ hữu hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1.2. Khấu hao lũy kế TSCĐ hữu hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2. GTCL Tài sản thuê tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2.1. Nguyên giá tài sản thuê tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2.2. Khấu hao lũy kế tài sản thuê tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3. GTCL tài sản cố định vô hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3.1. Nguyên giá TSCĐ vô hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3.2. Khấu khao lũy kế TSCĐ vô hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.4. Xây dựng cơ bản dở dang (trước 2015)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Giá trị ròng tài sản đầu tư\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.1. Nguyên giá tài sản đầu tư\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.2. Khấu hao lũy kế tài sản đầu tư\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tài sản dở dang dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4.1. Chi phí sản xuất, kinh doanh dở dang dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4.2. Xây dựng cơ bản dở dang\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Đầu tư dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.1. Đầu tư vào các công ty con\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.2. Đầu tư vào các công ty liên kết\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.3. Đầu tư dài hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.4. Dự phòng giảm giá đầu tư dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.5. Đầu tư nắm giữ đến ngày đáo hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Lợi thế thương mại (trước 2015)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tài sản dài hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.1. Trả trước dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.2. Tài sản thuế thu nhập hoãn lại\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.3. Thiết bị, vật tư, phụ tùng thay thế dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.4. Các tài sản dài hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.5. Lợi thế thương mại\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'A. TỔNG CỘNG TÀI SẢN\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'I. NỢ PHẢI TRẢ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Nợ ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1. Phải trả người bán ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.2. Người mua trả tiền trước ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.3. Thuế và các khoản phải trả Nhà nước\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.4. Phải trả người lao động\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.5. Chi phí phải trả ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.6. Phải trả nội bộ ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.7. Phải trả theo tiến độ kế hoạch hợp đồng xây dựng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.8. Doanh thu chưa thực hiện ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.9. Phải trả khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.10. Vay và nợ thuê tài chính ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.11. Dự phòng các khoản phải trả ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.12. Quỹ khen thưởng, phúc lợi\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.13. Quỹ bình ổn giá\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.14. Giao dịch mua bán lại trái phiếu chính phủ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Nợ dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1. Phải trả nhà cung cấp dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2. Người mua trả tiền trước dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3. Chi phí phải trả dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.4. Phải trả nội bộ về vốn kinh doanh\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.5. Phải trả nội bộ dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.6. Doanh thu chưa thực hiện dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.7. Phải trả dài hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.8. Vay và nợ thuê tài chính dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.9. Trái phiếu chuyển đổi\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.10. Cổ phiếu ưu đãi\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.11. Thuế thu nhập hoãn lại phải trả\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.12. Dự phòng trợ cấp thôi việc\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.13. Dự phòng phải trả dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.14. Quỹ phát triển khoa học công nghệ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'II. VỐN CHỦ SỞ HỮU\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Vốn và các quỹ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1. Vốn góp của chủ sở hữu\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1.1 Cổ phiếu phổ thông có quyền biểu quyết\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1.2. Cổ phiếu ưu đãi\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.2. Thặng dư vốn cổ phần\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.3. Quyền chọn chuyển đổi trái phiếu\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.4. Vốn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.5. Cổ phiếu quỹ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.6. Chênh lệch đánh giá lại tài sản\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.7. Chênh lệch tỷ giá\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.8. Quỹ đầu tư và phát triển\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.9. Quỹ hỗ trợ sắp xếp doanh nghiệp\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.10. Quỹ dự phòng tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.11. Quỹ khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.12. Lãi chưa phân phối\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.12.1. LNST chưa phân phối lũy kế đến cuối kỳ trước\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.12.2. LNST chưa phân phối kỳ này\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.13. Nguồn vốn đầu tư XDCB\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.14. Lợi ích cổ đông không kiểm soát\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Nguồn kinh phí và quỹ khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1. Quỹ khen thưởng, phúc lợi (trước 2010)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2. Nguồn kinh phí\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3. Nguồn kinh phí đã hình thành TSCĐ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'III. LỢI ÍCH CỦA CỔ ĐÔNG KHÔNG KIỂM SOÁT (trước 2015)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'B. TỔNG CỘNG NGUỒN VỐN\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Doanh thu bán hàng và cung cấp dịch vụ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Các khoản giảm trừ doanh thu\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Doanh thu thuần\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Giá vốn hàng bán\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Lợi nhuận gộp về bán hàng và cung cấp dịch vụ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Doanh thu hoạt động tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Chi phí tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.1. Trong đó: Chi phí lãi vay\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '8. Lãi/lỗ từ công ty liên doanh\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '9. Chi phí bán hàng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '10. Chi phí quản lý doanh  nghiệp\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '11. Lợi nhuận thuần từ hoạt động kinh doanh\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '12. Thu nhập khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '13. Chi phí khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '14. Lợi nhuận khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '15. Lãi/lỗ từ công ty liên doanh (trước 2015)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '16. Tổng lợi nhuận kế toán trước thuế\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '17. Chi phí thuế thu nhập doanh nghiệp\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '17.1. Thuế thu nhập doanh nghiệp - hiện thời\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '17.2. Thuế thu nhập doanh nghiệp - hoãn lại\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '18. Lợi nhuận sau thuế thu nhập doanh nghiệp\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '19. Lợi ích của cổ đông thiểu số\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '20. Cổ đông của Công ty mẹ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '21. Lãi cơ bản trên cổ phiếu\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '22. Lãi suy giảm trên cổ phiếu\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'I. Lưu chuyển tiền thuần từ hoạt động kinh doanh (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Lợi nhuận trước thuế (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Khấu hao TSCĐ và BĐSĐT (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Phân bổ lợi thế thương mại (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Chi phí dự phòng (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Lãi/lỗ chênh lệch tỷ giá hối đoái do đánh giá lại các khoản mục tiền tệ có gốc ngoại tệ (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Lãi/lỗ từ thanh lý tài sản cố định (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Lãi/lỗ từ hoạt động đầu tư (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '8. Chi phí lãi vay (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '9. Thu lãi và cổ tức  (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '10. Các khoản điều chỉnh khác  (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '11. Lợi nhuận từ hoạt động kinh doanh trước thay đổi vốn lưu động  (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '12. Tăng/giảm các khoản phải thu  (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '13. Tăng/giảm hàng tồn kho  (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '14. Tăng/giảm các khoản phải trả (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '15. Tăng/giảm chi phí trả trước (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '16. Tăng/giảm chứng khoán kinh doanh (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '17. Chi phí lãi vay đã trả (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '18. Thuế thu nhập doanh nghiệp đã trả (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '19. Tiền thu khác từ các hoạt động kinh doanh (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '20. Tiền chi khác từ các hoạt động kinh doanh (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'II. Lưu chuyển tiền thuần từ hoạt động đầu tư (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền chi để mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tiền thu từ thanh lý, nhượng bán TSCĐ và các tài sản dài hạn khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Tiền chi cho vay, mua các công cụ nợ của đợn vị khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tiền thu hồi cho vay, bán lại các công cụ nợ của đơn vị khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tiền chi đầu tư góp vốn vào đơn vị khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Tiền thu hồi đầu tư góp vốn vào đơn vị khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia (GT)\nHợp nhất\nQuý: Hàng năm\n\n',
 'III. Lưu chuyển tiền thuần từ hoạt động tài chính (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền thu từ phát hành cổ phiếu, nhận góp vốn của chủ sở hữu (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tiền trả lại vốn góp cho các chủ sở hữu, mua lại cổ phiếu của doanh nghiệp đã phát hành (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Tiền thu được các khoản đi vay (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tiền trả nợ gốc vay (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tiền thanh toán vốn gốc đi thuê tài chính (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Cổ tức đã trả (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tiền lãi đã nhận (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'IV. Lưu chuyển tiền thuần trong kỳ (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'V. Tiền và tương đương tiền đầu kỳ (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'VI. Ảnh hưởng của chênh lệch tỷ giá (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'VII. Tiền và tương đương tiền cuối kỳ (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'I. Lưu chuyển tiền tệ ròng từ các hoạt động sản xuất kinh doanh (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền thu từ bán hàng, Cung cấp dịch vụ và DT khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tiền chi trả cho người cung cấp HH và dịch vụ (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Tiền chi trả cho người lao động (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tiền chi trả lãi vay (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tiền chi nộp thuế thu nhập doanh nghiệp (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Tiền thu từ hoạt động kinh doanh (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tiền chi khác cho hoạt động kinh doanh (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'II. Lưu chuyển tiền tệ ròng từ hoạt động đầu tư (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền chi để mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tiền thu từ thanh lý, nhượng bán TSCĐ và các tài sản dài hạn khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Tiền chi cho vay, mua các công cụ nợ của đợn vị khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tiền thu hồi cho vay, bán lại các công cụ nợ của đơn vị khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tiền chi đầu tư góp vốn vào đơn vị khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Tiền thu hồi đầu tư góp vốn vào đơn vị khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'III. Lưu chuyển tiền tệ từ hoạt động tài chính (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền thu từ phát hành cổ phiếu, nhận góp vốn của chủ sở hữu (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tiền trả lại vốn góp cho các chủ sở hữu, mua lại cổ phiếu của doanh nghiệp đã phát hành (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Tiền thu được các khoản đi vay (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tiền trả nợ gốc vay (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tiền thanh toán vốn gốc đi thuê tài chính (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Cổ tức đã trả (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tiền lãi đã nhận (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'IV. Lưu chuyển tiền thuần trong kỳ (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'V. Tiền và tương đương tiền đầu kỳ (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'VI. Ảnh hưởng của chênh lệch tỷ giá (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'VII. Tiền và tương đương tiền cuối kỳ (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND']

In [11]:
pl.DataFrame(
    {
        "a": [1, 2, 3],
        "b": [1, 2, 3],
        "c": [1, 2, 3],
    }
).rename({"e": "d", "c": "d"}, strict=False).select([pl.col("a"), pl.col("d")])

shape: (3, 2)
┌─────┬─────┐
│ a   ┆ d   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 1   │
│ 2   ┆ 2   │
│ 3   ┆ 3   │
└─────┴─────┘

In [12]:
rename_mapping = {
    "Mã": "ticker",
    "Sàn": "exchange",
    "I. TÀI SẢN NGẮN HẠN\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "CA",
    "1. Tiền và tương đương tiền \nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "cash",
    "3. Các khoản phải thu ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "s_rec",
    "3.1. Phải thu ngắn hạn của khách hàng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "s_traderec",
    "4. Hàng tồn kho, ròng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "inventory",
    "II. TÀI SẢN DÀI HẠN\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "NCA",
    "1. Phải thu dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "l_rec",
    "1.1. Phải thu khách hang dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "l_traderec",
    "1.1. Phải thu khách hàng dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "l_traderec",
    "2.1. GTCL TSCĐ hữu hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "ppe",
    "A. TỔNG CỘNG TÀI SẢN\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "TA",
    "I. NỢ PHẢI TRẢ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "TL",
    "1. Nợ ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "CL",
    "1.1. Phải trả người bán ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "s_tradepay",
    "2. Nợ dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "NCL",
    "2.1. Phải trả nhà cung cấp dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "l_tradepay",
    "II. VỐN CHỦ SỞ HỮU\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "equity",
    "1.12. Lãi chưa phân phối\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "RE",
    "1. Doanh thu bán hàng và cung cấp dịch vụ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "sales",
    "3. Doanh thu thuần\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "netsales",
    "4. Giá vốn hàng bán\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "cogs",
    "5. Lợi nhuận gộp về bán hàng và cung cấp dịch vụ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "grossprofit",
    "9. Chi phí bán hàng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "sellingexp",
    "10. Chi phí quản lý doanh  nghiệp\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "GAexp",
    "10. Chi phí quản lý doanh nghiệp\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "GAexp",
    "11. Lợi nhuận thuần từ hoạt động kinh doanh\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "operatingprofit",
    "16. Tổng lợi nhuận kế toán trước thuế\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "ebt",
    "18. Lợi nhuận sau thuế thu nhập doanh nghiệp\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "netprofit",
    "I. Lưu chuyển tiền thuần từ hoạt động kinh doanh (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "cfo",
    "2. Khấu hao TSCĐ và BĐSĐT (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "dep",
    "6. Cổ tức đã trả (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND": "div",
}

for file in (DATA_DIR / "BCTC/XLXS").iterdir():
    # df = pl.read_excel(DATA_DIR / "BCTC/XLXS/2016.xlsx")
    print(file)
    df = pl.read_excel(file)
    df.rename(rename_mapping, strict=False).select(list(set(rename_mapping.values())))

/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2021.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2017.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2016.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2020.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2007.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2011.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2010.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2013.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2009.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2008.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2012.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2019.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2023.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2015.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2014.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2022.xlsx
/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2018.xlsx

In [13]:
pl.read_excel("/Users/Naot/kristal-thesis-not-mine/data/BCTC/XLXS/2023.xlsx").columns

['STT',
 'Mã',
 'Tên công ty',
 'Sàn',
 'year',
 'I. TÀI SẢN NGẮN HẠN\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền và tương đương tiền \nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1. Tiền\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.2. Các khoản tương đương tiền\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Đầu tư tài chính ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1. Chứng khoán kinh doanh\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2. Dự phòng giảm giá chứng khoán kinh doanh\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3. Đầu tư nắm giữ đến ngày đáo hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Các khoản phải thu ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.1. Phải thu ngắn hạn của khách hàng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.2. Trả trước cho người bán ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.3. Phải thu nội bộ ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.4. Phải thu theo tiến độ kế hoạch hợp đồng xây dựng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.5. Phải thu về cho vay ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.6. Phải thu ngắn hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.7. Dự phòng phải thu ngắn hạn khó đòi\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.8. Tài sản thiếu chờ xử lý\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Hàng tồn kho, ròng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4.1. Hàng tồn kho\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4.2. Dự phòng giảm giá HTK\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tài sản ngắn hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.1. Chi phí trả trước ngắn hạn \nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.2. Thuế GTGT được khấu trừ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.3. Thuế và các khoản khác phải thu Nhà nước\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.4. Giao dịch mua bán lại trái phiếu chính phủ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.5. Tài sản ngắn hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'II. TÀI SẢN DÀI HẠN\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Phải thu dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1. Phải thu khách hàng dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.2. Trả trước người bán dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.3. Vốn kinh doanh ở các đơn vị trực thuộc\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.4. Phải thu nội bộ dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.5. Phải thu về cho vay dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.6. Phải thu dài hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.7. Dự phòng phải thu dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tài sản cố định\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1. GTCL TSCĐ hữu hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1.1. Nguyên giá TSCĐ hữu hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1.2. Khấu hao lũy kế TSCĐ hữu hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2. GTCL Tài sản thuê tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2.1. Nguyên giá tài sản thuê tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2.2. Khấu hao lũy kế tài sản thuê tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3. GTCL tài sản cố định vô hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3.1. Nguyên giá TSCĐ vô hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3.2. Khấu khao lũy kế TSCĐ vô hình\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.4. Xây dựng cơ bản dở dang (trước 2015)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Giá trị ròng tài sản đầu tư\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.1. Nguyên giá tài sản đầu tư\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3.2. Khấu hao lũy kế tài sản đầu tư\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tài sản dở dang dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4.1. Chi phí sản xuất, kinh doanh dở dang dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4.2. Xây dựng cơ bản dở dang\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Đầu tư dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.1. Đầu tư vào các công ty con\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.2. Đầu tư vào các công ty liên kết\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.3. Đầu tư dài hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.4. Dự phòng giảm giá đầu tư dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5.5. Đầu tư nắm giữ đến ngày đáo hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Lợi thế thương mại (trước 2015)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tài sản dài hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.1. Trả trước dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.2. Tài sản thuế thu nhập hoãn lại\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.3. Thiết bị, vật tư, phụ tùng thay thế dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.4. Các tài sản dài hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.5. Lợi thế thương mại\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'A. TỔNG CỘNG TÀI SẢN\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'I. NỢ PHẢI TRẢ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Nợ ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1. Phải trả người bán ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.2. Người mua trả tiền trước ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.3. Thuế và các khoản phải trả Nhà nước\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.4. Phải trả người lao động\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.5. Chi phí phải trả ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.6. Phải trả nội bộ ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.7. Phải trả theo tiến độ kế hoạch hợp đồng xây dựng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.8. Doanh thu chưa thực hiện ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.9. Phải trả khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.10. Vay và nợ thuê tài chính ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.11. Dự phòng các khoản phải trả ngắn hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.12. Quỹ khen thưởng, phúc lợi\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.13. Quỹ bình ổn giá\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.14. Giao dịch mua bán lại trái phiếu chính phủ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Nợ dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1. Phải trả nhà cung cấp dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2. Người mua trả tiền trước dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3. Chi phí phải trả dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.4. Phải trả nội bộ về vốn kinh doanh\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.5. Phải trả nội bộ dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.6. Doanh thu chưa thực hiện dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.7. Phải trả dài hạn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.8. Vay và nợ thuê tài chính dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.9. Trái phiếu chuyển đổi\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.10. Cổ phiếu ưu đãi\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.11. Thuế thu nhập hoãn lại phải trả\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.12. Dự phòng trợ cấp thôi việc\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.13. Dự phòng phải trả dài hạn\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.14. Quỹ phát triển khoa học công nghệ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'II. VỐN CHỦ SỞ HỮU\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Vốn và các quỹ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1. Vốn góp của chủ sở hữu\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1.1 Cổ phiếu phổ thông có quyền biểu quyết\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.1.2. Cổ phiếu ưu đãi\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.2. Thặng dư vốn cổ phần\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.3. Quyền chọn chuyển đổi trái phiếu\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.4. Vốn khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.5. Cổ phiếu quỹ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.6. Chênh lệch đánh giá lại tài sản\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.7. Chênh lệch tỷ giá\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.8. Quỹ đầu tư và phát triển\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.9. Quỹ hỗ trợ sắp xếp doanh nghiệp\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.10. Quỹ dự phòng tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.11. Quỹ khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.12. Lãi chưa phân phối\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.12.1. LNST chưa phân phối lũy kế đến cuối kỳ trước\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.12.2. LNST chưa phân phối kỳ này\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.13. Nguồn vốn đầu tư XDCB\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1.14. Lợi ích cổ đông không kiểm soát\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Nguồn kinh phí và quỹ khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.1. Quỹ khen thưởng, phúc lợi (trước 2010)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.2. Nguồn kinh phí\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2.3. Nguồn kinh phí đã hình thành TSCĐ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'III. LỢI ÍCH CỦA CỔ ĐÔNG KHÔNG KIỂM SOÁT (trước 2015)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'B. TỔNG CỘNG NGUỒN VỐN\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Doanh thu bán hàng và cung cấp dịch vụ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Các khoản giảm trừ doanh thu\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Doanh thu thuần\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Giá vốn hàng bán\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Lợi nhuận gộp về bán hàng và cung cấp dịch vụ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Doanh thu hoạt động tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Chi phí tài chính\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7.1. Trong đó: Chi phí lãi vay\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '8. Lãi/lỗ từ công ty liên doanh\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '9. Chi phí bán hàng\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '10. Chi phí quản lý doanh nghiệp\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '11. Lợi nhuận thuần từ hoạt động kinh doanh\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '12. Thu nhập khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '13. Chi phí khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '14. Lợi nhuận khác\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '15. Lãi/lỗ từ công ty liên doanh (trước 2015)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '16. Tổng lợi nhuận kế toán trước thuế\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '17. Chi phí thuế thu nhập doanh nghiệp\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '17.1. Thuế thu nhập doanh nghiệp - hiện thời\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '17.2. Thuế thu nhập doanh nghiệp - hoãn lại\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '18. Lợi nhuận sau thuế thu nhập doanh nghiệp\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '19. Lợi ích của cổ đông thiểu số\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '20. Cổ đông của Công ty mẹ\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '21. Lãi cơ bản trên cổ phiếu\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '22. Lãi suy giảm trên cổ phiếu\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'I. Lưu chuyển tiền thuần từ hoạt động kinh doanh (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Lợi nhuận trước thuế (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Khấu hao TSCĐ và BĐSĐT (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Phân bổ lợi thế thương mại (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Chi phí dự phòng (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Lãi/lỗ chênh lệch tỷ giá hối đoái do đánh giá lại các khoản mục tiền tệ có gốc ngoại tệ (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Lãi/lỗ từ thanh lý tài sản cố định (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Lãi/lỗ từ hoạt động đầu tư (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '8. Chi phí lãi vay (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '9. Thu lãi và cổ tức  (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '10. Các khoản điều chỉnh khác  (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '11. Lợi nhuận từ hoạt động kinh doanh trước thay đổi vốn lưu động  (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '12. Tăng/giảm các khoản phải thu  (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '13. Tăng/giảm hàng tồn kho  (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '14. Tăng/giảm các khoản phải trả (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '15. Tăng/giảm chi phí trả trước (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '16. Tăng/giảm chứng khoán kinh doanh (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '17. Chi phí lãi vay đã trả (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '18. Thuế thu nhập doanh nghiệp đã trả (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '19. Tiền thu khác từ các hoạt động kinh doanh (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '20. Tiền chi khác từ các hoạt động kinh doanh (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'II. Lưu chuyển tiền thuần từ hoạt động đầu tư (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền chi để mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tiền thu từ thanh lý, nhượng bán TSCĐ và các tài sản dài hạn khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Tiền chi cho vay, mua các công cụ nợ của đợn vị khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tiền thu hồi cho vay, bán lại các công cụ nợ của đơn vị khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tiền chi đầu tư góp vốn vào đơn vị khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Tiền thu hồi đầu tư góp vốn vào đơn vị khác (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia (GT)\nHợp nhất\nQuý: Hàng năm\n\n',
 'III. Lưu chuyển tiền thuần từ hoạt động tài chính (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền thu từ phát hành cổ phiếu, nhận góp vốn của chủ sở hữu (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tiền trả lại vốn góp cho các chủ sở hữu, mua lại cổ phiếu của doanh nghiệp đã phát hành (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Tiền thu được các khoản đi vay (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tiền trả nợ gốc vay (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tiền thanh toán vốn gốc đi thuê tài chính (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Cổ tức đã trả (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tiền lãi đã nhận (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'IV. Lưu chuyển tiền thuần trong kỳ (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'V. Tiền và tương đương tiền đầu kỳ (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'VI. Ảnh hưởng của chênh lệch tỷ giá (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'VII. Tiền và tương đương tiền cuối kỳ (GT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'I. Lưu chuyển tiền tệ ròng từ các hoạt động sản xuất kinh doanh (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền thu từ bán hàng, Cung cấp dịch vụ và DT khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tiền chi trả cho người cung cấp HH và dịch vụ (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Tiền chi trả cho người lao động (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tiền chi trả lãi vay (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tiền chi nộp thuế thu nhập doanh nghiệp (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Tiền thu từ hoạt động kinh doanh (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tiền chi khác cho hoạt động kinh doanh (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'II. Lưu chuyển tiền tệ ròng từ hoạt động đầu tư (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền chi để mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tiền thu từ thanh lý, nhượng bán TSCĐ và các tài sản dài hạn khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Tiền chi cho vay, mua các công cụ nợ của đợn vị khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tiền thu hồi cho vay, bán lại các công cụ nợ của đơn vị khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tiền chi đầu tư góp vốn vào đơn vị khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Tiền thu hồi đầu tư góp vốn vào đơn vị khác (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'III. Lưu chuyển tiền tệ từ hoạt động tài chính (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '1. Tiền thu từ phát hành cổ phiếu, nhận góp vốn của chủ sở hữu (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '2. Tiền trả lại vốn góp cho các chủ sở hữu, mua lại cổ phiếu của doanh nghiệp đã phát hành (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '3. Tiền thu được các khoản đi vay (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '4. Tiền trả nợ gốc vay (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '5. Tiền thanh toán vốn gốc đi thuê tài chính (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '6. Cổ tức đã trả (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 '7. Tiền lãi đã nhận (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'IV. Lưu chuyển tiền thuần trong kỳ (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'V. Tiền và tương đương tiền đầu kỳ (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'VI. Ảnh hưởng của chênh lệch tỷ giá (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND',
 'VII. Tiền và tương đương tiền cuối kỳ (TT)\nHợp nhất\nQuý: Hàng năm\n\nĐơn vị: VND']

In [14]:
df = pl.read_parquet(PROCESSED_DATA_DIR / "financials.parquet")

df.group_by("exchange").agg(pl.len().alias("count"))

shape: (2, 2)
┌──────────┬───────┐
│ exchange ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ HNX      ┆ 5354  │
│ HOSE     ┆ 7134  │
└──────────┴───────┘

In [15]:
pl.read_excel(
    DATA_DIR / "data_gpr_export.xls", columns=["month", "GPR", "GPRT", "GPRA"]
).with_columns(
    [
        pl.col("month"),
        pl.col("GPR").cast(pl.Float64),
        pl.col("GPRA").cast(pl.Float64),
        pl.col("GPRT").cast(pl.Float64),
    ]
)

Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 2, falling back to string
Could not determine dtype for column 3, falling back to string

shape: (1_516, 4)
┌────────────┬────────────┬────────────┬────────────┐
│ month      ┆ GPR        ┆ GPRT       ┆ GPRA       │
│ ---        ┆ ---        ┆ ---        ┆ ---        │
│ date       ┆ f64        ┆ f64        ┆ f64        │
╞════════════╪════════════╪════════════╪════════════╡
│ 1900-01-01 ┆ null       ┆ null       ┆ null       │
│ 1900-02-01 ┆ null       ┆ null       ┆ null       │
│ 1900-03-01 ┆ null       ┆ null       ┆ null       │
│ 1900-04-01 ┆ null       ┆ null       ┆ null       │
│ 1900-05-01 ┆ null       ┆ null       ┆ null       │
│ …          ┆ …          ┆ …          ┆ …          │
│ 2025-12-01 ┆ 130.955856 ┆ 144.906235 ┆ 121.788544 │
│ 2026-01-01 ┆ 168.629868 ┆ 220.171417 ┆ 100.222099 │
│ 2026-02-01 ┆ 120.745155 ┆ 157.467438 ┆ 81.679771  │
│ 2026-03-01 ┆ 326.989105 ┆ 316.379272 ┆ 445.254486 │
│ 2026-04-01 ┆ 230.770752 ┆ 252.264908 ┆ 285.348083 │
└────────────┴────────────┴────────────┴────────────┘

In [16]:
price_df = pl.read_parquet(PROCESSED_DATA_DIR / "price.parquet")

price_df

shape: (2_382_075, 6)
┌────────┬────────────┬──────────┬─────────┬────────────┬────────────────┐
│ ticker ┆ date       ┆ close    ┆ volume  ┆ shares     ┆ mktcap         │
│ ---    ┆ ---        ┆ ---      ┆ ---     ┆ ---        ┆ ---            │
│ str    ┆ date       ┆ f64      ┆ i64     ┆ i64        ┆ i64            │
╞════════╪════════════╪══════════╪═════════╪════════════╪════════════════╡
│ AAA    ┆ 2018-12-28 ┆ 11536.08 ┆ 1257250 ┆ 171199976  ┆ 2516639647200  │
│ AAM    ┆ 2018-12-28 ┆ 8690.97  ┆ 50      ┆ 8035701    ┆ 107678393400   │
│ ABR    ┆ 2018-12-28 ┆ 3614.97  ┆ 100     ┆ 3000000    ┆ 12300000000    │
│ ABT    ┆ 2018-12-28 ┆ 26370.64 ┆ 1350    ┆ 11497257   ┆ 462189731400   │
│ ACB    ┆ 2018-12-28 ┆ 7864.52  ┆ 2559551 ┆ 1247165130 ┆ 36916087848000 │
│ …      ┆ …          ┆ …        ┆ …       ┆ …          ┆ …              │
│ VIG    ┆ 2022-01-04 ┆ 17700.0  ┆ 1330695 ┆ 34133300   ┆ 604159410000   │
│ VIT    ┆ 2022-01-04 ┆ 21428.46 ┆ 15737   ┆ 49999664   ┆ 1169992137600  │
│ VLA    ┆ 2022-01-04 ┆ 10379.33 ┆ 55400   ┆ 1080000    ┆ 32400000000    │
│ VMC    ┆ 2022-01-04 ┆ 21043.6  ┆ 73434   ┆ 20000000   ┆ 550000000000   │
│ VMS    ┆ 2022-01-04 ┆ 15403.48 ┆ 50      ┆ 8999998    ┆ 159299964600   │
└────────┴────────────┴──────────┴─────────┴────────────┴────────────────┘

In [17]:
icb_df = pl.read_parquet(PROCESSED_DATA_DIR / "icb.parquet")

icb_df

shape: (732, 6)
┌────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┐
│ ticker ┆ icb1            ┆ icb2            ┆ icb3            ┆ icb4            ┆ icb5            │
│ ---    ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             │
│ str    ┆ str             ┆ str             ┆ str             ┆ str             ┆ str             │
╞════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╡
│ AAA    ┆ Nguyên vật liệu ┆ Hóa chất        ┆ Hóa chất        ┆ Nhựa, cao su &  ┆ Nhựa            │
│        ┆                 ┆                 ┆                 ┆ sợi             ┆                 │
│ AAM    ┆ Hàng Tiêu dùng  ┆ Thực phẩm và đồ ┆ Sản xuất thực   ┆ Nuôi trồng nông ┆ Nuôi trồng thủy │
│        ┆                 ┆ uống            ┆ phẩm            ┆ & hải sản       ┆ hải sản         │
│ AAT    ┆ Hàng Tiêu dùng  ┆ Hàng cá nhân &  ┆ Hàng cá nhân    ┆ Hàng May mặc    ┆ Hàng May mặc    │
│        ┆                 ┆ Gia dụng        ┆                 ┆                 ┆                 │
│ ABR    ┆ Công nghiệp     ┆ Hàng & Dịch vụ  ┆ Tư vấn & Hỗ trợ ┆ Tư vấn & Hỗ trợ ┆ Tư vấn & Hỗ trợ │
│        ┆                 ┆ Công nghiệp     ┆ Kinh doanh      ┆ KD              ┆ KD              │
│ ABS    ┆ Hàng Tiêu dùng  ┆ Thực phẩm và đồ ┆ Sản xuất thực   ┆ Nuôi trồng nông ┆ Trồng ngũ cốc,  │
│        ┆                 ┆ uống            ┆ phẩm            ┆ & hải sản       ┆ rau, trái cây   │
│        ┆                 ┆                 ┆                 ┆                 ┆ &…              │
│ …      ┆ …               ┆ …               ┆ …               ┆ …               ┆ …               │
│ VTV    ┆ Công nghiệp     ┆ Xây dựng và Vật ┆ Xây dựng và Vật ┆ Vật liệu xây    ┆ Vật liệu xây    │
│        ┆                 ┆ liệu            ┆ liệu            ┆ dựng & Nội thất ┆ dựng khác       │
│ VTZ    ┆ Nguyên vật liệu ┆ Hóa chất        ┆ Hóa chất        ┆ Nhựa, cao su &  ┆ Nhựa            │
│        ┆                 ┆                 ┆                 ┆ sợi             ┆                 │
│ WCS    ┆ Công nghiệp     ┆ Hàng & Dịch vụ  ┆ Vận tải         ┆ Kho bãi, hậu    ┆ Bến xe khách    │
│        ┆                 ┆ Công nghiệp     ┆                 ┆ cần và bảo      ┆                 │
│        ┆                 ┆                 ┆                 ┆ dưỡng           ┆                 │
│ WSS    ┆ Tài chính       ┆ Dịch vụ tài     ┆ Dịch vụ tài     ┆ Môi giới chứng  ┆ Môi giới chứng  │
│        ┆                 ┆ chính           ┆ chính           ┆ khoán           ┆ khoán           │
│ X20    ┆ Hàng Tiêu dùng  ┆ Hàng cá nhân &  ┆ Hàng cá nhân    ┆ Hàng May mặc    ┆ Hàng May mặc    │
│        ┆                 ┆ Gia dụng        ┆                 ┆                 ┆                 │
└────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┘

In [18]:
icb_df.select(pl.col("ticker")).height == icb_df.select(
    pl.col("ticker").unique()
).height

True

In [19]:
price_df

shape: (2_382_075, 6)
┌────────┬────────────┬──────────┬─────────┬────────────┬────────────────┐
│ ticker ┆ date       ┆ close    ┆ volume  ┆ shares     ┆ mktcap         │
│ ---    ┆ ---        ┆ ---      ┆ ---     ┆ ---        ┆ ---            │
│ str    ┆ date       ┆ f64      ┆ i64     ┆ i64        ┆ i64            │
╞════════╪════════════╪══════════╪═════════╪════════════╪════════════════╡
│ AAA    ┆ 2018-12-28 ┆ 11536.08 ┆ 1257250 ┆ 171199976  ┆ 2516639647200  │
│ AAM    ┆ 2018-12-28 ┆ 8690.97  ┆ 50      ┆ 8035701    ┆ 107678393400   │
│ ABR    ┆ 2018-12-28 ┆ 3614.97  ┆ 100     ┆ 3000000    ┆ 12300000000    │
│ ABT    ┆ 2018-12-28 ┆ 26370.64 ┆ 1350    ┆ 11497257   ┆ 462189731400   │
│ ACB    ┆ 2018-12-28 ┆ 7864.52  ┆ 2559551 ┆ 1247165130 ┆ 36916087848000 │
│ …      ┆ …          ┆ …        ┆ …       ┆ …          ┆ …              │
│ VIG    ┆ 2022-01-04 ┆ 17700.0  ┆ 1330695 ┆ 34133300   ┆ 604159410000   │
│ VIT    ┆ 2022-01-04 ┆ 21428.46 ┆ 15737   ┆ 49999664   ┆ 1169992137600  │
│ VLA    ┆ 2022-01-04 ┆ 10379.33 ┆ 55400   ┆ 1080000    ┆ 32400000000    │
│ VMC    ┆ 2022-01-04 ┆ 21043.6  ┆ 73434   ┆ 20000000   ┆ 550000000000   │
│ VMS    ┆ 2022-01-04 ┆ 15403.48 ┆ 50      ┆ 8999998    ┆ 159299964600   │
└────────┴────────────┴──────────┴─────────┴────────────┴────────────────┘

In [20]:
price_df.join(
    icb_df.select(pl.col("ticker")),
    on="ticker",
    how="anti",
    # validate="m:1",
).select(pl.col("ticker").unique())

shape: (6, 1)
┌────────┐
│ ticker │
│ ---    │
│ str    │
╞════════╡
│ CST    │
│ BSR    │
│ PTX    │
│ MIC    │
│ CAR    │
│ DSC    │
└────────┘

In [21]:
cleaned_price_df = (
    price_df.join(
        icb_df,
        on="ticker",
        how="left",
        validate="m:1",
    )
    .filter(pl.col("icb2").is_not_null())
    .filter(
        ~pl.col("icb2").is_in(
            [
                "Dịch vụ tài chính",
                "Ngân hàng",
                "Bảo hiểm",
            ]
        )
    )
    .filter(~pl.col("ticker").is_in(["DSC", "MIC"]))
    .with_columns(
        [
            pl.col("date").dt.year().alias("year"),
            pl.col("date").dt.week().alias("week"),
            pl.col("date").dt.weekday().alias("dayofweek"),
        ]
    )
    .filter(~pl.col("dayofweek").is_in([6, 7]))
    .filter(pl.col("year") >= 2010)
    .filter(pl.col("year") <= 2024)
    .filter(~pl.col("close").is_null())
    .sort("ticker", "date")
)
cleaned_price_df

shape: (1_944_378, 14)
┌────────┬────────────┬──────────┬──────────┬───┬────────────────────────┬──────┬──────┬───────────┐
│ ticker ┆ date       ┆ close    ┆ volume   ┆ … ┆ icb5                   ┆ year ┆ week ┆ dayofweek │
│ ---    ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---                    ┆ ---  ┆ ---  ┆ ---       │
│ str    ┆ date       ┆ f64      ┆ i64      ┆   ┆ str                    ┆ i32  ┆ i8   ┆ i8        │
╞════════╪════════════╪══════════╪══════════╪═══╪════════════════════════╪══════╪══════╪═══════════╡
│ AAA    ┆ 2010-07-15 ┆ 10446.61 ┆ 174100   ┆ … ┆ Nhựa                   ┆ 2010 ┆ 28   ┆ 4         │
│ AAA    ┆ 2010-07-16 ┆ 9755.75  ┆ 109200   ┆ … ┆ Nhựa                   ┆ 2010 ┆ 28   ┆ 5         │
│ AAA    ┆ 2010-07-19 ┆ 9818.55  ┆ 144900   ┆ … ┆ Nhựa                   ┆ 2010 ┆ 29   ┆ 1         │
│ AAA    ┆ 2010-07-20 ┆ 9462.66  ┆ 328700   ┆ … ┆ Nhựa                   ┆ 2010 ┆ 29   ┆ 2         │
│ AAA    ┆ 2010-07-21 ┆ 9441.72  ┆ 95800    ┆ … ┆ Nhựa                   ┆ 2010 ┆ 29   ┆ 3         │
│ …      ┆ …          ┆ …        ┆ …        ┆ … ┆ …                      ┆ …    ┆ …    ┆ …         │
│ YEG    ┆ 2024-12-25 ┆ 21174.64 ┆ 4708716  ┆ … ┆ Giải trí & Truyền      ┆ 2024 ┆ 52   ┆ 3         │
│        ┆            ┆          ┆          ┆   ┆ thông                  ┆      ┆      ┆           │
│ YEG    ┆ 2024-12-26 ┆ 19714.32 ┆ 6636173  ┆ … ┆ Giải trí & Truyền      ┆ 2024 ┆ 52   ┆ 4         │
│        ┆            ┆          ┆          ┆   ┆ thông                  ┆      ┆      ┆           │
│ YEG    ┆ 2024-12-27 ┆ 18345.27 ┆ 452948   ┆ … ┆ Giải trí & Truyền      ┆ 2024 ┆ 52   ┆ 5         │
│        ┆            ┆          ┆          ┆   ┆ thông                  ┆      ┆      ┆           │
│ YEG    ┆ 2024-12-30 ┆ 18254.0  ┆ 14448825 ┆ … ┆ Giải trí & Truyền      ┆ 2024 ┆ 1    ┆ 1         │
│        ┆            ┆          ┆          ┆   ┆ thông                  ┆      ┆      ┆           │
│ YEG    ┆ 2024-12-31 ┆ 16976.22 ┆ 4284261  ┆ … ┆ Giải trí & Truyền      ┆ 2024 ┆ 1    ┆ 2         │
│        ┆            ┆          ┆          ┆   ┆ thông                  ┆      ┆      ┆           │
└────────┴────────────┴──────────┴──────────┴───┴────────────────────────┴──────┴──────┴───────────┘

In [22]:
cleaned_price_df.describe()

shape: (9, 15)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ ticker  ┆ date      ┆ close     ┆ … ┆ icb5      ┆ year      ┆ week      ┆ dayofweek │
│ ---        ┆ ---     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str     ┆ str       ┆ f64       ┆   ┆ str       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 1944378 ┆ 1944378   ┆ 1.944378e ┆ … ┆ 1944378   ┆ 1.944378e ┆ 1.944378e ┆ 1.944378e │
│            ┆         ┆           ┆ 6         ┆   ┆           ┆ 6         ┆ 6         ┆ 6         │
│ null_count ┆ 0       ┆ 0         ┆ 0.0       ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ null    ┆ 2018-04-2 ┆ 14503.490 ┆ … ┆ null      ┆ 2017.8079 ┆ 27.346484 ┆ 3.012244  │
│            ┆         ┆ 8 11:24:3 ┆ 205       ┆   ┆           ┆ 97        ┆           ┆           │
│            ┆         ┆ 6.457355  ┆           ┆   ┆           ┆           ┆           ┆           │
│ std        ┆ null    ┆ null      ┆ 17826.264 ┆ … ┆ null      ┆ 4.188662  ┆ 14.920561 ┆ 1.409844  │
│            ┆         ┆           ┆ 437       ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ AAA     ┆ 2010-01-0 ┆ 0.0       ┆ … ┆ Bao bì,   ┆ 2010.0    ┆ 1.0       ┆ 1.0       │
│            ┆         ┆ 4         ┆           ┆   ┆ đóng gói  ┆           ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆ bằng nhựa ┆           ┆           ┆           │
│ 25%        ┆ null    ┆ 2014-11-1 ┆ 4893.74   ┆ … ┆ null      ┆ 2014.0    ┆ 14.0      ┆ 2.0       │
│            ┆         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 50%        ┆ null    ┆ 2018-09-1 ┆ 8918.55   ┆ … ┆ null      ┆ 2018.0    ┆ 28.0      ┆ 3.0       │
│            ┆         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 75%        ┆ null    ┆ 2021-12-0 ┆ 16827.48  ┆ … ┆ null      ┆ 2021.0    ┆ 40.0      ┆ 4.0       │
│            ┆         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│ max        ┆ YEG     ┆ 2024-12-3 ┆ 377075.95 ┆ … ┆ Đồ gia    ┆ 2024.0    ┆ 53.0      ┆ 5.0       │
│            ┆         ┆ 1         ┆           ┆   ┆ dụng một  ┆           ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆ lần       ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [23]:
cleaned_price_df.sort("ticker", "date").with_columns(
    pl.col("date").shift(1).over("ticker").alias("prev_date")
).with_columns(
    (pl.col("date") - pl.col("prev_date")).dt.total_days().alias("day_gap")
).filter(pl.col("day_gap").is_null()).height == cleaned_price_df.select(
    pl.col("ticker").unique()
).height

True

In [24]:
(
    cleaned_price_df.sort("ticker", "date")
    .with_columns(pl.col("date").shift(1).over("ticker").alias("prev_date"))
    .with_columns(pl.col("date").shift(-1).over("ticker").alias("next_date"))
    .with_columns(
        (pl.col("date") - pl.col("prev_date")).dt.total_days().alias("day_gap")
    )
    # .filter(pl.col("ticker") == "VHM")
    # .sort("date")
    .filter((pl.col("day_gap") > 24.0))
    .select("ticker", "close", "day_gap", "date", "prev_date")
    # .describe()
)

shape: (7, 5)
┌────────┬──────────┬─────────┬────────────┬────────────┐
│ ticker ┆ close    ┆ day_gap ┆ date       ┆ prev_date  │
│ ---    ┆ ---      ┆ ---     ┆ ---        ┆ ---        │
│ str    ┆ f64      ┆ i64     ┆ date       ┆ date       │
╞════════╪══════════╪═════════╪════════════╪════════════╡
│ GEE    ┆ 36901.8  ┆ 27      ┆ 2024-08-14 ┆ 2024-07-18 │
│ HU1    ┆ 3867.36  ┆ 29      ┆ 2011-11-03 ┆ 2011-10-05 │
│ L40    ┆ 17692.22 ┆ 2541    ┆ 2021-01-27 ┆ 2014-02-12 │
│ PDN    ┆ 3658.83  ┆ 90      ┆ 2011-10-26 ┆ 2011-07-28 │
│ TCO    ┆ 2091.62  ┆ 74      ┆ 2012-02-27 ┆ 2011-12-15 │
│ TDP    ┆ 14041.9  ┆ 73      ┆ 2020-10-12 ┆ 2020-07-31 │
│ VHM    ┆ 64363.4  ┆ 308     ┆ 2018-05-17 ┆ 2017-07-13 │
└────────┴──────────┴─────────┴────────────┴────────────┘

In [25]:
(
    cleaned_price_df.sort("ticker", "date")
    .with_columns(
        pl.col("close").shift(1).over("ticker").alias("prev_close"),
    )
    .with_columns(
        (pl.col("close") / pl.col("prev_close")).log().alias("dret"),
    )
    .with_columns(
        pl.when(pl.col("mktcap") == 0)
        .then(None)
        .otherwise(pl.col("mktcap"))
        .alias("mktcap"),
    )
    .with_columns(
        pl.col("date").dt.year().alias("year"),
        pl.col("date").dt.week().alias("week"),
    )
    .group_by("ticker", "year", "week")
    .agg(
        pl.col("dret").sum(),
        pl.col("mktcap").last().fill_null(strategy="backward").last().alias("mktcap"),
        pl.col("icb1").last().fill_null(strategy="backward").last(),
        pl.col("icb2").last().fill_null(strategy="backward").last(),
        pl.col("icb3").last().fill_null(strategy="backward").last(),
        pl.col("icb4").last().fill_null(strategy="backward").last(),
        pl.col("icb5").last().fill_null(strategy="backward").last(),
    )
)

shape: (402_022, 10)
┌────────┬──────┬──────┬─────────────┬───┬──────────────┬──────────────┬─────────────┬─────────────┐
│ ticker ┆ year ┆ week ┆ dret        ┆ … ┆ icb2         ┆ icb3         ┆ icb4        ┆ icb5        │
│ ---    ┆ ---  ┆ ---  ┆ ---         ┆   ┆ ---          ┆ ---          ┆ ---         ┆ ---         │
│ str    ┆ i32  ┆ i8   ┆ f64         ┆   ┆ str          ┆ str          ┆ str         ┆ str         │
╞════════╪══════╪══════╪═════════════╪═══╪══════════════╪══════════════╪═════════════╪═════════════╡
│ KOS    ┆ 2018 ┆ 6    ┆ -0.107892   ┆ … ┆ Bất động sản ┆ Bất động sản ┆ Bất động    ┆ Bất động    │
│        ┆      ┆      ┆             ┆   ┆              ┆              ┆ sản         ┆ sản dân cư  │
│ ADP    ┆ 2014 ┆ 15   ┆ 0.0         ┆ … ┆ Xây dựng và  ┆ Xây dựng và  ┆ Vật liệu    ┆ Sơn và chất │
│        ┆      ┆      ┆             ┆   ┆ Vật liệu     ┆ Vật liệu     ┆ xây dựng &  ┆ phủ         │
│        ┆      ┆      ┆             ┆   ┆              ┆              ┆ Nội thất    ┆             │
│ ADC    ┆ 2024 ┆ 12   ┆ 0.059083    ┆ … ┆ Truyền thông ┆ Truyền thông ┆ Sách, ấn    ┆ Sách, ấn    │
│        ┆      ┆      ┆             ┆   ┆              ┆              ┆ bản & sản   ┆ bản & sản   │
│        ┆      ┆      ┆             ┆   ┆              ┆              ┆ phẩm văn    ┆ phẩm văn    │
│        ┆      ┆      ┆             ┆   ┆              ┆              ┆ hó…         ┆ hó…         │
│ TTC    ┆ 2019 ┆ 2    ┆ -0.034887   ┆ … ┆ Xây dựng và  ┆ Xây dựng và  ┆ Vật liệu    ┆ Sản xuất    │
│        ┆      ┆      ┆             ┆   ┆ Vật liệu     ┆ Vật liệu     ┆ xây dựng &  ┆ gạch ốp lát │
│        ┆      ┆      ┆             ┆   ┆              ┆              ┆ Nội thất    ┆ & Vật liệ…  │
│ HAD    ┆ 2017 ┆ 39   ┆ 0.021819    ┆ … ┆ Thực phẩm và ┆ Bia và đồ    ┆ Sản xuất    ┆ Sản xuất    │
│        ┆      ┆      ┆             ┆   ┆ đồ uống      ┆ uống         ┆ bia         ┆ bia         │
│ …      ┆ …    ┆ …    ┆ …           ┆ … ┆ …            ┆ …            ┆ …           ┆ …           │
│ CMG    ┆ 2019 ┆ 3    ┆ 0.063873    ┆ … ┆ Công nghệ    ┆ Phần mềm &   ┆ Dịch vụ Máy ┆ Dịch vụ Máy │
│        ┆      ┆      ┆             ┆   ┆ Thông tin    ┆ Dịch vụ Máy  ┆ tính        ┆ tính        │
│        ┆      ┆      ┆             ┆   ┆              ┆ tính         ┆             ┆             │
│ PET    ┆ 2012 ┆ 17   ┆ 0.07696     ┆ … ┆ Bán lẻ       ┆ Bán lẻ       ┆ Phân phối   ┆ Phân phối   │
│        ┆      ┆      ┆             ┆   ┆              ┆              ┆ hàng chuyên ┆ hàng chuyên │
│        ┆      ┆      ┆             ┆   ┆              ┆              ┆ dụng        ┆ dụng        │
│ PV2    ┆ 2021 ┆ 21   ┆ -0.057158   ┆ … ┆ Bất động sản ┆ Bất động sản ┆ Bất động    ┆ Bất động    │
│        ┆      ┆      ┆             ┆   ┆              ┆              ┆ sản         ┆ sản dân cư  │
│ VE1    ┆ 2011 ┆ 49   ┆ -9.7145e-17 ┆ … ┆ Xây dựng và  ┆ Xây dựng và  ┆ Xây dựng    ┆ Xây dựng    │
│        ┆      ┆      ┆             ┆   ┆ Vật liệu     ┆ Vật liệu     ┆             ┆             │
│ MCP    ┆ 2012 ┆ 27   ┆ -0.020478   ┆ … ┆ Hàng & Dịch  ┆ Hàng công    ┆ Containers  ┆ Bao bì,     │
│        ┆      ┆      ┆             ┆   ┆ vụ Công      ┆ nghiệp       ┆ & Đóng gói  ┆ đóng gói    │
│        ┆      ┆      ┆             ┆   ┆ nghiệp       ┆              ┆             ┆ kim loại    │
└────────┴──────┴──────┴─────────────┴───┴──────────────┴──────────────┴─────────────┴─────────────┘

In [ ]:
cleaned_price_df = (
    price_df.join(
        icb_df,
        on="ticker",
        how="left",
        validate="m:1",
    )
    .filter(pl.col("icb2").is_not_null())
    .filter(
        ~pl.col("icb2").is_in(
            [
                "Dịch vụ tài chính",
                "Ngân hàng",
                "Bảo hiểm",
            ]
        )
    )
    .filter(~pl.col("ticker").is_in(["DSC", "MIC"]))
    .with_columns(
        pl.when(pl.col("mktcap") != 0)
        .then(pl.col("mktcap"))
        .otherwise(None)
        .alias("mktcap"),
        year=pl.col("date").dt.year(),
        week=pl.col("date").dt.week(),
        dayofweek=pl.col("date").dt.weekday(),
    )
    .filter(~pl.col("dayofweek").is_in([6, 7]))
    .filter(pl.col("year") >= 2010)
    .filter(pl.col("year") <= 2024)
)
cleaned_price_df

shape: (2_012_272, 14)
┌────────┬────────────┬──────────┬─────────┬───┬─────────────────────────┬──────┬──────┬───────────┐
│ ticker ┆ date       ┆ close    ┆ volume  ┆ … ┆ icb5                    ┆ year ┆ week ┆ dayofweek │
│ ---    ┆ ---        ┆ ---      ┆ ---     ┆   ┆ ---                     ┆ ---  ┆ ---  ┆ ---       │
│ str    ┆ date       ┆ f64      ┆ i64     ┆   ┆ str                     ┆ i32  ┆ i8   ┆ i8        │
╞════════╪════════════╪══════════╪═════════╪═══╪═════════════════════════╪══════╪══════╪═══════════╡
│ AAA    ┆ 2018-12-28 ┆ 11536.08 ┆ 1257250 ┆ … ┆ Nhựa                    ┆ 2018 ┆ 52   ┆ 5         │
│ AAM    ┆ 2018-12-28 ┆ 8690.97  ┆ 50      ┆ … ┆ Nuôi trồng thủy hải sản ┆ 2018 ┆ 52   ┆ 5         │
│ ABR    ┆ 2018-12-28 ┆ 3614.97  ┆ 100     ┆ … ┆ Tư vấn & Hỗ trợ KD      ┆ 2018 ┆ 52   ┆ 5         │
│ ABT    ┆ 2018-12-28 ┆ 26370.64 ┆ 1350    ┆ … ┆ Nuôi trồng thủy hải sản ┆ 2018 ┆ 52   ┆ 5         │
│ ACC    ┆ 2018-12-28 ┆ 5718.26  ┆ 40      ┆ … ┆ Sản xuất bê tông        ┆ 2018 ┆ 52   ┆ 5         │
│ …      ┆ …          ┆ …        ┆ …       ┆ … ┆ …                       ┆ …    ┆ …    ┆ …         │
│ VIF    ┆ 2022-01-04 ┆ 17585.17 ┆ 0       ┆ … ┆ Lâm sản và Chế biến gỗ  ┆ 2022 ┆ 1    ┆ 2         │
│ VIT    ┆ 2022-01-04 ┆ 21428.46 ┆ 15737   ┆ … ┆ Sản xuất gạch ốp lát &  ┆ 2022 ┆ 1    ┆ 2         │
│        ┆            ┆          ┆         ┆   ┆ Vật liệ…                ┆      ┆      ┆           │
│ VLA    ┆ 2022-01-04 ┆ 10379.33 ┆ 55400   ┆ … ┆ Phần mềm                ┆ 2022 ┆ 1    ┆ 2         │
│ VMC    ┆ 2022-01-04 ┆ 21043.6  ┆ 73434   ┆ … ┆ Xây dựng                ┆ 2022 ┆ 1    ┆ 2         │
│ VMS    ┆ 2022-01-04 ┆ 15403.48 ┆ 50      ┆ … ┆ Dịch vụ kho bãi         ┆ 2022 ┆ 1    ┆ 2         │
└────────┴────────────┴──────────┴─────────┴───┴─────────────────────────┴──────┴──────┴───────────┘

In [ ]:
wret_df = (
    cleaned_price_df.sort(["ticker", "date"])
    .upsample(time_column="date", every="1d", group_by="ticker", maintain_order=True)
    .with_columns(
        dret=(pl.col("close") / pl.col("close").shift(1)).log().over("ticker")
    )
    .filter(pl.col("close").is_not_null() | pl.col("dret").is_not_null())
    .group_by(["ticker", "year", "week"], maintain_order=True)
    .agg(
        [
            pl.col("dret").sum(),
            pl.col("mktcap").last(ignore_nulls=True),
            pl.col("icb1").last(ignore_nulls=True),
            pl.col("icb2").last(ignore_nulls=True),
            pl.col("icb3").last(ignore_nulls=True),
            pl.col("icb4").last(ignore_nulls=True),
            pl.col("icb5").last(ignore_nulls=True),
        ]
    )
    # 6. Calculate weekly return and filter outliers
    .with_columns(wret=(pl.col("dret").exp() - 1))
    .filter(pl.col("wret").abs() < (pow(1.1, 5) - 1))
)
wret_df

shape: (401_964, 11)
┌────────┬──────┬──────┬───────────┬───┬──────────────┬────────────────┬───────────────┬───────────┐
│ ticker ┆ year ┆ week ┆ dret      ┆ … ┆ icb3         ┆ icb4           ┆ icb5          ┆ wret      │
│ ---    ┆ ---  ┆ ---  ┆ ---       ┆   ┆ ---          ┆ ---            ┆ ---           ┆ ---       │
│ str    ┆ i32  ┆ i8   ┆ f64       ┆   ┆ str          ┆ str            ┆ str           ┆ f64       │
╞════════╪══════╪══════╪═══════════╪═══╪══════════════╪════════════════╪═══════════════╪═══════════╡
│ AAA    ┆ 2010 ┆ 28   ┆ -0.068421 ┆ … ┆ Hóa chất     ┆ Nhựa, cao su & ┆ Nhựa          ┆ -0.066132 │
│        ┆      ┆      ┆           ┆   ┆              ┆ sợi            ┆               ┆           │
│ AAA    ┆ 2010 ┆ 29   ┆ -0.008565 ┆ … ┆ Hóa chất     ┆ Nhựa, cao su & ┆ Nhựa          ┆ -0.008529 │
│        ┆      ┆      ┆           ┆   ┆              ┆ sợi            ┆               ┆           │
│ AAA    ┆ 2010 ┆ 30   ┆ 0.056918  ┆ … ┆ Hóa chất     ┆ Nhựa, cao su & ┆ Nhựa          ┆ 0.058569  │
│        ┆      ┆      ┆           ┆   ┆              ┆ sợi            ┆               ┆           │
│ AAA    ┆ 2010 ┆ 31   ┆ -0.004073 ┆ … ┆ Hóa chất     ┆ Nhựa, cao su & ┆ Nhựa          ┆ -0.004065 │
│        ┆      ┆      ┆           ┆   ┆              ┆ sợi            ┆               ┆           │
│ AAA    ┆ 2010 ┆ 32   ┆ -0.091767 ┆ … ┆ Hóa chất     ┆ Nhựa, cao su & ┆ Nhựa          ┆ -0.087682 │
│        ┆      ┆      ┆           ┆   ┆              ┆ sợi            ┆               ┆           │
│ …      ┆ …    ┆ …    ┆ …         ┆ … ┆ …            ┆ …              ┆ …             ┆ …         │
│ YEG    ┆ 2024 ┆ 48   ┆ 0.041577  ┆ … ┆ Truyền thông ┆ Giải trí &     ┆ Giải trí &    ┆ 0.042453  │
│        ┆      ┆      ┆           ┆   ┆              ┆ Truyền thông   ┆ Truyền thông  ┆           │
│ YEG    ┆ 2024 ┆ 49   ┆ 0.183066  ┆ … ┆ Truyền thông ┆ Giải trí &     ┆ Giải trí &    ┆ 0.200893  │
│        ┆      ┆      ┆           ┆   ┆              ┆ Truyền thông   ┆ Truyền thông  ┆           │
│ YEG    ┆ 2024 ┆ 50   ┆ 0.024098  ┆ … ┆ Truyền thông ┆ Giải trí &     ┆ Giải trí &    ┆ 0.024391  │
│        ┆      ┆      ┆           ┆   ┆              ┆ Truyền thông   ┆ Truyền thông  ┆           │
│ YEG    ┆ 2024 ┆ 51   ┆ 0.263417  ┆ … ┆ Truyền thông ┆ Giải trí &     ┆ Giải trí &    ┆ 0.30137   │
│        ┆      ┆      ┆           ┆   ┆              ┆ Truyền thông   ┆ Truyền thông  ┆           │
│ YEG    ┆ 2024 ┆ 52   ┆ -0.009901 ┆ … ┆ Truyền thông ┆ Giải trí &     ┆ Giải trí &    ┆ -0.009852 │
│        ┆      ┆      ┆           ┆   ┆              ┆ Truyền thông   ┆ Truyền thông  ┆           │
└────────┴──────┴──────┴───────────┴───┴──────────────┴────────────────┴───────────────┴───────────┘

In [ ]:
vwmktret_df = (
    wret_df
    # Value-weighted market return
    .sort("ticker", "year", "week")
    .with_columns(
        pl.col("mktcap").sum().over("year", "week").alias("totalmktcap"),
    )
    .with_columns(
        (pl.col("mktcap") / pl.col("totalmktcap")).alias("mktcap_weighted"),
    )
    .with_columns(
        pl.int_range(1, pl.len() + 1).over("ticker").alias("weekid"),
    )
    .with_columns(
        pl.col("mktcap_weighted").shift(1).over("ticker").alias("mktcap_weighted_L1"),
    )
    .with_columns(
        (pl.col("mktcap_weighted_L1") * pl.col("wret")).alias("wret_weighted"),
    )
    .with_columns(
        pl.col("wret_weighted").sum().over("year", "week").alias("vwmktret"),
    )
    # Value-weighted industry return
    # .with_columns(
    #     pl.col("mktcap").sum().over(["icb1", "year", "week"]).alias("total_mktcap_ind")
    # )
    # .with_columns((pl.col("mktcap") / pl.col("total_mktcap_ind")).alias("ind_weight"))
    # .with_columns(pl.col("ind_weight").shift(1).over("ticker").alias("ind_weight_L1"))
    # .with_columns((pl.col("ind_weight_L1") * pl.col("wret")).alias("ind_wret_weighted"))
    # .with_columns(
    #     pl.col("ind_wret_weighted")
    #     .sum()
    #     .over(["icb1", "year", "week"])
    #     .alias("vwindret")
    # )
    # .with_columns(
    #     [
    #         pl.col("vwmktret").shift(1).over("ticker").alias("vwmktret_L1"),
    #         pl.col("vwmktret").shift(-1).over("ticker").alias("vwmktret_F1"),
    #         pl.col("vwindret").shift(1).over("ticker").alias("vwindret_L1"),
    #         pl.col("vwindret").shift(-1).over("ticker").alias("vwindret_F1"),
    #     ]
    # )
)
vwmktret_df

In [ ]:
# Wrap the columns into a struct Series, then check
is_sorted = (
    cleaned_price_df.select(pl.struct("ticker", "weekid")).to_series().is_sorted()
)

print(is_sorted)

True