In [1]:
import polars as pl
import pandas as pd
from pathlib import Path

In [2]:
DATA_DIR = Path("../data").absolute().resolve()

print(DATA_DIR)
assert DATA_DIR.exists()

/Users/Naot/kristal-thesis-not-mine/data

In [3]:
df = pl.read_excel(DATA_DIR / "HOSE/Excel/101-200_HNX_2007-2010.xlsx")

df

Could not determine dtype for column 8, falling back to string

shape: (21_482, 28)
┌───────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ No    ┆ Ticker ┆ Company    ┆ Date       ┆ … ┆ Volume     ┆ Average    ┆ Average    ┆ Average    │
│ ---   ┆ ---    ┆ Name       ┆ ---        ┆   ┆ weighted   ┆ Volume 1   ┆ Volume 1   ┆ Volume 1   │
│ i64   ┆ str    ┆ ---        ┆ date       ┆   ┆ average    ┆ week       ┆ month      ┆ year       │
│       ┆        ┆ str        ┆            ┆   ┆ price …    ┆ Unit: Sh…  ┆ Unit: S…   ┆ Unit: Sh…  │
│       ┆        ┆            ┆            ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│       ┆        ┆            ┆            ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞═══════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 1     ┆ ICG    ┆ Song Hong  ┆ 2010-12-31 ┆ … ┆ 28625      ┆ 244340     ┆ 555452     ┆ 405546     │
│       ┆        ┆ Constructi ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ on         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 2     ┆ IDJ    ┆ IDJ Invest ┆ 2010-12-31 ┆ … ┆ null       ┆ 595080     ┆ 1092400    ┆ null       │
│       ┆        ┆ ment., JSC ┆            ┆   ┆            ┆            ┆            ┆            │
│ 3     ┆ IDV    ┆ Vinh Phuc  ┆ 2010-12-31 ┆ … ┆ null       ┆ 2380       ┆ 943        ┆ null       │
│       ┆        ┆ Infrastruc ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ ture       ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ Devel…     ┆            ┆   ┆            ┆            ┆            ┆            │
│ 4     ┆ INC    ┆ IDICO      ┆ 2010-12-31 ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│       ┆        ┆ Investment ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ Consultanc ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ y          ┆            ┆   ┆            ┆            ┆            ┆            │
│ 5     ┆ INN    ┆ Agricultur ┆ 2010-12-31 ┆ … ┆ null       ┆ 700        ┆ 2095       ┆ null       │
│       ┆        ┆ e Printing ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ And Packa… ┆            ┆   ┆            ┆            ┆            ┆            │
│ …     ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 21478 ┆ PJC    ┆ Petrolimex ┆ 2007-01-02 ┆ … ┆ null       ┆ 0          ┆ null       ┆ null       │
│       ┆        ┆ Hanoi Tran ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ sportatio… ┆            ┆   ┆            ┆            ┆            ┆            │
│ 21479 ┆ PLC    ┆ Petrolimex ┆ 2007-01-02 ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│       ┆        ┆ Petrochemi ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ cal        ┆            ┆   ┆            ┆            ┆            ┆            │
│ 21480 ┆ POT    ┆ Post and   ┆ 2007-01-02 ┆ … ┆ null       ┆ 37900      ┆ null       ┆ null       │
│       ┆        ┆ Telecom    ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ Equipments ┆            ┆   ┆            ┆            ┆            ┆            │
│ 21481 ┆ PSC    ┆ Sai Gon    ┆ 2007-01-02 ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│       ┆        ┆ Petrolimex ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ Transporta ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ t…         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 21482 ┆ PTS    ┆ Hai Phong  ┆ 2007-01-02 ┆ … ┆ null       ┆ 2925       ┆ 3452       ┆ null       │
│       ┆        ┆ Petrolimex ┆            ┆   ┆            ┆            ┆            ┆            │
│       ┆        ┆ Transport… ┆            ┆   ┆            ┆            ┆            ┆            │
└───────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [4]:
df.select(pl.col("Adjusted Rate (D)\nUnit: %").n_unique())

shape: (1, 1)
┌───────────────────┐
│ Adjusted Rate (D) │
│ Unit: %           │
│ ---               │
│ u32               │
╞═══════════════════╡
│ 1                 │
└───────────────────┘

In [5]:
df.columns

['No',
 'Ticker',
 'Company Name',
 'Date',
 'Close Adjusted (D)\nUnit: VND',
 'Total trading volume (D)\nUnit: Shares',
 'Reference Adjusted (D)\nUnit: VND',
 '% Change (D)\nUnit: %',
 'Adjusted Rate (D)\nUnit: %',
 'Weighted Average Outstanding Shares\nUnit: Shares',
 'Weighted Average Diluted Outstanding Shares\nUnit: Shares',
 'Current Outstanding Shares\nUnit: Shares',
 'Market Capitalization \nUnit: VND',
 '% Price Change 1 day\nUnit: %',
 '% Price Change 1 week\nUnit: %',
 '% Price Change 1 month\nUnit: %',
 '% Price Change 1 year\nUnit: %',
 'Price Change 1 day\nUnit: VND',
 'Price Change 1 week\nUnit: VND',
 'Price Change 1 month\nUnit: VND',
 'Price Change 1 year\nUnit: VND',
 'Volume weighted average price (VWAP) 1 day\nUnit: VND',
 'Volume weighted average price (VWAP) 1 week\nUnit: VND',
 'Volume weighted average price (VWAP) 1 month\nUnit: VND',
 'Volume weighted average price (VWAP) 1 year\nUnit: VND',
 'Average Volume 1 week\nUnit: Shares',
 'Average Volume 1 month\nUnit: Shares',
 'Average Volume 1 year\nUnit: Shares']

In [21]:
df1 = pd.read_stata(DATA_DIR/"temp/1-100_hnx_2007-2010.xlsx.dta")
df1 = pl.from_pandas(df1)
df1 = df1.with_columns(pl.col("date").cast(pl.Date))
df1 = df1.with_columns(pl.col("volume").cast(pl.Int64))
df1 = df1.with_columns(pl.col("shares").cast(pl.Int64))
df1 = df1.with_columns(pl.col("mktcap").cast(pl.Int64))
df1

shape: (27_346, 6)
┌────────┬────────────┬─────────┬────────┬──────────┬──────────────┐
│ ticker ┆ date       ┆ close   ┆ volume ┆ shares   ┆ mktcap       │
│ ---    ┆ ---        ┆ ---     ┆ ---    ┆ ---      ┆ ---          │
│ str    ┆ date       ┆ f64     ┆ i64    ┆ i64      ┆ i64          │
╞════════╪════════════╪═════════╪════════╪══════════╪══════════════╡
│ ADC    ┆ 2010-12-31 ┆ 1141.27 ┆ 1000   ┆ 1000000  ┆ 10100000000  │
│ ALT    ┆ 2010-12-31 ┆ 8139.37 ┆ 24000  ┆ 5114618  ┆ 90017276800  │
│ AMC    ┆ 2010-12-31 ┆ null    ┆ null   ┆ null     ┆ null         │
│ AME    ┆ 2010-12-31 ┆ 6407.1  ┆ 19700  ┆ 12000000 ┆ 108000000000 │
│ AMV    ┆ 2010-12-31 ┆ 5126.21 ┆ 23100  ┆ 2100000  ┆ 27720000000  │
│ …      ┆ …          ┆ …       ┆ …      ┆ …        ┆ …            │
│        ┆ null       ┆ null    ┆ null   ┆ null     ┆ null         │
│        ┆ null       ┆ null    ┆ null   ┆ null     ┆ null         │
│        ┆ null       ┆ null    ┆ null   ┆ null     ┆ null         │
│        ┆ null       ┆ null    ┆ null   ┆ null     ┆ null         │
│        ┆ null       ┆ null    ┆ null   ┆ null     ┆ null         │
└────────┴────────────┴─────────┴────────┴──────────┴──────────────┘

In [22]:
df2 = pl.read_parquet(DATA_DIR.parent / "processed/cleanup/1-100_HNX_2007-2010.parquet")
df2

shape: (27_335, 6)
┌────────┬────────────┬──────────┬────────┬──────────┬──────────────┐
│ ticker ┆ date       ┆ close    ┆ volume ┆ shares   ┆ mktcap       │
│ ---    ┆ ---        ┆ ---      ┆ ---    ┆ ---      ┆ ---          │
│ str    ┆ date       ┆ f64      ┆ i64    ┆ i64      ┆ i64          │
╞════════╪════════════╪══════════╪════════╪══════════╪══════════════╡
│ ADC    ┆ 2010-12-31 ┆ 1141.27  ┆ 1000   ┆ 1000000  ┆ 10100000000  │
│ ALT    ┆ 2010-12-31 ┆ 8139.37  ┆ 24000  ┆ 5114618  ┆ 90017276800  │
│ AMC    ┆ 2010-12-31 ┆ null     ┆ null   ┆ null     ┆ null         │
│ AME    ┆ 2010-12-31 ┆ 6407.1   ┆ 19700  ┆ 12000000 ┆ 108000000000 │
│ AMV    ┆ 2010-12-31 ┆ 5126.21  ┆ 23100  ┆ 2100000  ┆ 27720000000  │
│ …      ┆ …          ┆ …        ┆ …      ┆ …        ┆ …            │
│ CMC    ┆ 2007-01-02 ┆ 13736.85 ┆ 900    ┆ null     ┆ null         │
│ CTB    ┆ 2007-01-02 ┆ 2952.37  ┆ 0      ┆ null     ┆ null         │
│ DAE    ┆ 2007-01-02 ┆ 5988.2   ┆ 300    ┆ null     ┆ null         │
│ EBS    ┆ 2007-01-02 ┆ 4778.69  ┆ 12200  ┆ null     ┆ null         │
│ HJS    ┆ 2007-01-02 ┆ 5399.03  ┆ 1800   ┆ null     ┆ null         │
└────────┴────────────┴──────────┴────────┴──────────┴──────────────┘

In [24]:
df1.join(df2, on=df1.columns, how="anti")

shape: (13_130, 6)
┌────────┬────────────┬───────┬────────┬─────────┬────────┐
│ ticker ┆ date       ┆ close ┆ volume ┆ shares  ┆ mktcap │
│ ---    ┆ ---        ┆ ---   ┆ ---    ┆ ---     ┆ ---    │
│ str    ┆ date       ┆ f64   ┆ i64    ┆ i64     ┆ i64    │
╞════════╪════════════╪═══════╪════════╪═════════╪════════╡
│ AMC    ┆ 2010-12-31 ┆ null  ┆ null   ┆ null    ┆ null   │
│ BAB    ┆ 2010-12-31 ┆ null  ┆ null   ┆ null    ┆ null   │
│ BCF    ┆ 2010-12-31 ┆ null  ┆ null   ┆ null    ┆ null   │
│ BSC    ┆ 2010-12-31 ┆ null  ┆ null   ┆ 3000000 ┆ 0      │
│ CEO    ┆ 2010-12-31 ┆ null  ┆ null   ┆ null    ┆ null   │
│ …      ┆ …          ┆ …     ┆ …      ┆ …       ┆ …      │
│        ┆ null       ┆ null  ┆ null   ┆ null    ┆ null   │
│        ┆ null       ┆ null  ┆ null   ┆ null    ┆ null   │
│        ┆ null       ┆ null  ┆ null   ┆ null    ┆ null   │
│        ┆ null       ┆ null  ┆ null   ┆ null    ┆ null   │
│        ┆ null       ┆ null  ┆ null   ┆ null    ┆ null   │
└────────┴────────────┴───────┴────────┴─────────┴────────┘

In [25]:
df2.join(df1, on=df2.columns, how="anti")

shape: (13_119, 6)
┌────────┬────────────┬──────────┬────────┬─────────┬────────┐
│ ticker ┆ date       ┆ close    ┆ volume ┆ shares  ┆ mktcap │
│ ---    ┆ ---        ┆ ---      ┆ ---    ┆ ---     ┆ ---    │
│ str    ┆ date       ┆ f64      ┆ i64    ┆ i64     ┆ i64    │
╞════════╪════════════╪══════════╪════════╪═════════╪════════╡
│ AMC    ┆ 2010-12-31 ┆ null     ┆ null   ┆ null    ┆ null   │
│ BAB    ┆ 2010-12-31 ┆ null     ┆ null   ┆ null    ┆ null   │
│ BCF    ┆ 2010-12-31 ┆ null     ┆ null   ┆ null    ┆ null   │
│ BSC    ┆ 2010-12-31 ┆ null     ┆ null   ┆ 3000000 ┆ 0      │
│ CEO    ┆ 2010-12-31 ┆ null     ┆ null   ┆ null    ┆ null   │
│ …      ┆ …          ┆ …        ┆ …      ┆ …       ┆ …      │
│ CMC    ┆ 2007-01-02 ┆ 13736.85 ┆ 900    ┆ null    ┆ null   │
│ CTB    ┆ 2007-01-02 ┆ 2952.37  ┆ 0      ┆ null    ┆ null   │
│ DAE    ┆ 2007-01-02 ┆ 5988.2   ┆ 300    ┆ null    ┆ null   │
│ EBS    ┆ 2007-01-02 ┆ 4778.69  ┆ 12200  ┆ null    ┆ null   │
│ HJS    ┆ 2007-01-02 ┆ 5399.03  ┆ 1800   ┆ null    ┆ null   │
└────────┴────────────┴──────────┴────────┴─────────┴────────┘

In [26]:
left_only = df1.join(df2, on=df1.columns, how="anti")
right_only = df2.join(df1, on=df1.columns, how="anti")
diff = pl.concat([left_only, right_only])
diff

shape: (26_249, 6)
┌────────┬────────────┬──────────┬────────┬─────────┬────────┐
│ ticker ┆ date       ┆ close    ┆ volume ┆ shares  ┆ mktcap │
│ ---    ┆ ---        ┆ ---      ┆ ---    ┆ ---     ┆ ---    │
│ str    ┆ date       ┆ f64      ┆ i64    ┆ i64     ┆ i64    │
╞════════╪════════════╪══════════╪════════╪═════════╪════════╡
│ AMC    ┆ 2010-12-31 ┆ null     ┆ null   ┆ null    ┆ null   │
│ BAB    ┆ 2010-12-31 ┆ null     ┆ null   ┆ null    ┆ null   │
│ BCF    ┆ 2010-12-31 ┆ null     ┆ null   ┆ null    ┆ null   │
│ BSC    ┆ 2010-12-31 ┆ null     ┆ null   ┆ 3000000 ┆ 0      │
│ CEO    ┆ 2010-12-31 ┆ null     ┆ null   ┆ null    ┆ null   │
│ …      ┆ …          ┆ …        ┆ …      ┆ …       ┆ …      │
│ CMC    ┆ 2007-01-02 ┆ 13736.85 ┆ 900    ┆ null    ┆ null   │
│ CTB    ┆ 2007-01-02 ┆ 2952.37  ┆ 0      ┆ null    ┆ null   │
│ DAE    ┆ 2007-01-02 ┆ 5988.2   ┆ 300    ┆ null    ┆ null   │
│ EBS    ┆ 2007-01-02 ┆ 4778.69  ┆ 12200  ┆ null    ┆ null   │
│ HJS    ┆ 2007-01-02 ┆ 5399.03  ┆ 1800   ┆ null    ┆ null   │
└────────┴────────────┴──────────┴────────┴─────────┴────────┘

In [28]:
fill = {"close": -1.0, "volume": -1, "shares": -1, "mktcap": -1}

left = df1.with_columns([pl.col(c).fill_null(v) for c, v in fill.items()])
right = df2.with_columns([pl.col(c).fill_null(v) for c, v in fill.items()])

left_only = left.join(right, on=left.columns, how="anti")
right_only = right.join(left, on=right.columns, how="anti")
diff = pl.concat([left_only, right_only])

diff

shape: (11, 6)
┌────────┬──────┬───────┬────────┬────────┬────────┐
│ ticker ┆ date ┆ close ┆ volume ┆ shares ┆ mktcap │
│ ---    ┆ ---  ┆ ---   ┆ ---    ┆ ---    ┆ ---    │
│ str    ┆ date ┆ f64   ┆ i64    ┆ i64    ┆ i64    │
╞════════╪══════╪═══════╪════════╪════════╪════════╡
│        ┆ null ┆ -1.0  ┆ -1     ┆ -1     ┆ -1     │
│        ┆ null ┆ -1.0  ┆ -1     ┆ -1     ┆ -1     │
│        ┆ null ┆ -1.0  ┆ -1     ┆ -1     ┆ -1     │
│        ┆ null ┆ -1.0  ┆ -1     ┆ -1     ┆ -1     │
│        ┆ null ┆ -1.0  ┆ -1     ┆ -1     ┆ -1     │
│ …      ┆ …    ┆ …     ┆ …      ┆ …      ┆ …      │
│        ┆ null ┆ -1.0  ┆ -1     ┆ -1     ┆ -1     │
│        ┆ null ┆ -1.0  ┆ -1     ┆ -1     ┆ -1     │
│        ┆ null ┆ -1.0  ┆ -1     ┆ -1     ┆ -1     │
│        ┆ null ┆ -1.0  ┆ -1     ┆ -1     ┆ -1     │
│        ┆ null ┆ -1.0  ┆ -1     ┆ -1     ┆ -1     │
└────────┴──────┴───────┴────────┴────────┴────────┘